### ISSUE TITLE
Is the fresh Eloquent method supported?

### ISSUE THREAD

**Issue by heydavid713** [Vinelab/NeoEloquent#100]
Hello,

I was reading through the Eloquent API documentation and I found the fresh method that returns a model from database. I tried using the method in NeoEloquent and it didn't work for me. 

Is there any planned support for this method in the future?

**Comment by Mulkave** [comment]
Can you please paste in the result/error you got ?

**Comment by tomb10516** [comment]
David,

Can you give me the test that didn't work with that?  I can turn it into a NeoEloquent functional test.  (David works with me and would have encountered the error while working on a project we are doing together, so he most likely tried the function inside a codebase I have access to.)

**Comment by Mulkave** [comment]
@tomb10516 @heydavid713 cool! I'll keep an eye on this so if you guys have progress please let me know.
