### ISSUE TITLE
HasOneOrMany::saveMany() needs type hint

### ISSUE THREAD

**Issue by tomb10516** [Vinelab/NeoEloquent#104]
saveMany() needs a type hint in order to be compatible with recent versions of Eloquent.

I'm going to skip a detailed bug report here because I am going to add a functional test that will fail when the bug is present and then do a PR including that test and a patch for the bug.

**Comment by tomb10516** [comment]
update:  the problem is a bit weirder than I thought at first.

The issue is really about compatibility with Laravel 5.0 versus 5.1  In 5.0 there is an array type hint that is lacking in NeoEloquent, but in 5.1 there must not be a type hint because the same function can take an array or a Collection in 5.1

We are running Laravel 5.0, but for some reason it looks like we are using illuminate/database version 5.1

Once I get this untangled I'll report back.

**Comment by tomb10516** [comment]
Clarification: the "we" in "We are running Laravel 5.0" is we = my company

**Comment by tomb10516** [comment]
I just confirmed that 77344ea58f breaks compatability with illuminate/database 5.0.

To replicate: change the 5.* for illuminate/database with 5.0 and you will get:

tomb@metal {(77344ea...)} ~/NeoEloquent$ ./vendor/phpunit/phpunit/phpunit  
PHPUnit 4.2.6 by Sebastian Bergmann.

Configuration read from /home/tomb/NeoEloquent/phpunit.xml

.............................................PHP Fatal error:  Call to a member function toArray() on array in /home/tomb/NeoEloquent/tests/Vinelab/NeoEloquent/Eloquent/BuilderTest.php on line 167
PHP Stack trace:
PHP   1. {main}() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/phpunit:56
PHP   3. PHPUnit_TextUI_Command->run() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:423
PHP   6. PHPUnit_Framework_TestSuite->run() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/Framework/TestSuite.php:703
PHP   7. PHPUnit_Framework_TestCase->run() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/Framework/TestSuite.php:703
PHP   8. PHPUnit_Framework_TestResult->run() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/Framework/TestCase.php:771
PHP   9. PHPUnit_Framework_TestCase->runBare() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/Framework/TestResult.php:643
PHP  10. PHPUnit_Framework_TestCase->runTest() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/Framework/TestCase.php:835
PHP  11. ReflectionMethod->invokeArgs() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/Framework/TestCase.php:963
PHP  12. Vinelab\NeoEloquent\Tests\Eloquent\EloquentBuilderTest->testListsReturnsTheMutatedAttributesOfAModel() /home/tomb/NeoEloquent/vendor/phpunit/phpunit/src/Framework/TestCase.php:963

**Comment by Mulkave** [comment]
@tomb10516 thanks for clarifying the issue, I've suspected this has to do with 5.0 and 5.1. Is there a chance for you (company) to upgrade to 5.1? since it is now the recommended version with its LTS announced.

**Comment by tomb10516** [comment]
I just finished upgrading our application to Laravel 5.1 and everything works fine.  Now that 1.2.6 explicitly requires 5.1 (in its composer.json) I think this issue is resolved.  If you haven't already you might want to announce that 1.2.6 does not support Laravel 5.0.

Thanks!

**Comment by Mulkave** [comment]
@tomb10516 thanks for the note, yes will do that.
