### ISSUE TITLE
How to define a relation that looks in both directions?

### ISSUE THREAD

**Issue by mvrsn** [Vinelab/NeoEloquent#107]
I'm fairly new to Neo4j, so I might be missing something, but is there any simple way to query both ways?

So far I've only found the `matchRelation()` method in the `Vinelab\NeoEloquent\Query\Builder` having any kind of reference to anything else other than `in` and `out` relations. It seems to support `in-out`, but I want to specify it as a Laravel relation rather than returning a `Builder` or a `ResultSet`. 

What I have now using attach is  `(User)-[:KNOWS]->(User)`, so I want to be able to define a relation that can get users using the `KNOWS` relation in both directions, but that will still allow me to use `->attach($model)` for example.

Is this possible in any simple way? :)

To clarify; the article below states that I should not create a relation that goes each way, which is what I feel the NeoEloquent wiki says I should do.

http://graphaware.com/neo4j/2013/10/11/neo4j-bidirectional-relationships.html

**Comment by tomb10516** [comment]
@hw2k 

Unfortunately I don't know of any efficient way to do this in NeoEloquent.  I believe it would require an extension to the grammar to do that efficiently.  If efficiency is not a concern the following will get you all users who are part of a friend relation regardless of which end of the directed edge they are on:

 $users = User::with('friend')->get();

This gets you what you want, but not efficiently.  It retrieves all users and then performs a second query to get both sides of all friend edges.  Specific example at bottom of this post.

If someone can thing of a clever way to express (n)-[:REL]-(n) in Eloquent like grammar I might take a shot at implementing.  I think this is in some ways related to the challenge of fitting edge attributes into searches and filters.

These are the raw Cypher queries generated by $users = User::with('friend')->get() with the following model and test code:

{"query":"MATCH (individual:`Individual`) RETURN *"}
{"query":"MATCH (individual:`Individual`), (individual)-[rel_friend_friend:FRIEND]->(friend:`Individual`) WHERE id(individual) IN [39, 40, 41] RETURN friend, individual","params":{"idindividual":41}}

class User extends Model
{

    protected $label = 'Individual';
    protected $fillable = ['name', 'email'];

    public function friend()
    {
        return $this->hasOne('Vinelab\NeoEloquent\Tests\Functional\Relations\HasOne\User', 'FRIEND');
    }
}

   public function testSavingBothWays()
    {
        $user1 = User::create(['name' => 'Alice', 'email' => 'A']);
        $user2 = User::create(['name' => 'Bob', 'email' => 'B']);
        $user3 = User::create(['name' => 'Charlie', 'email' => 'C']);

        $relation = $user1->friend()->attach($user2);
        $relation = $user3->friend()->attach($user2);
        
        $users = User::with('friend')->get();
        foreach ($users as $user) {
            print $user->name . " is a friend\n";
        }
    }

the printed output is:

Alice is a friend
Bob is a friend
Charlie is a friend

**Comment by mistenkt** [comment]
Your testSavingBothWays() function is faulty as you just list all users in the DB. You dont actually check that they have a relationship. 

Saving does not work both ways atm. And following your code, only user 1 and user 3 would have a friend, user 1 would not have any friends even tho two people are connected with him on the opposite direction.

**Comment by fzhan** [comment]
In many scenarios where an Object A could have a relationship to Object B in both directions, my question to this is also if there's a setup where we could search if AnyRelationshipExist(Object A, Object B) ?
