### ISSUE TITLE
Sending raw Cypher - Feature

### ISSUE THREAD

**Issue by wkolcz** [Vinelab/NeoEloquent#111]
Much like \DB::raw(), is there any chance you could add the ability to send raw Cypher to Neo4j and return and Object or Associative Array?

**Comment by cklouman** [comment]
+1

**Comment by Mulkave** [comment]
Related to: https://github.com/Vinelab/NeoEloquent/issues/26

**Comment by DanieleSottile** [comment]
+1

**Comment by matheusmariano** [comment]
+1

**Comment by terrapp** [comment]
+1

**Comment by imami** [comment]
+1

**Comment by decebal** [comment]
One can use the  \DB::getConnection()->statement($rawStatement), if need be

**Comment by prashantidealittechno** [comment]
Hello I try for the ``` $result = \DB::->statement($rawStatement) ``` but it return only true in $result.

**Comment by decebal** [comment]
@prashantidealittechno you're not missing anything , it returns a boolean about your operation status, as expected.
In case your expectations are different you might want to look at some other options, maybe `select` instead of `statement` would be a better candidate if you want something returned.

**Comment by LynX39** [comment]
+1
