### ISSUE TITLE
Check if two nodes already are related in specific relationship

### ISSUE THREAD

**Issue by luisalvarez** [Vinelab/NeoEloquent#112]
I don't find a way to get that i have a FOLLOWS realtionship in belongsToMany to get who follo me and hasMany to get who i follow.

but i wanna validated that a person can't follow twice other person because when use detach maybe just deteach one of the repeated relationship.

Any help ?

**Comment by Mulkave** [comment]
@luisalvarez so sorry for the late reply. If I understand your question correctly, you would like to know whether a given user (assumed by ID) already has a relationship with the name `FOLLOWS` to another user (assumed by ID).

You may use the `whereHas` relationship:

```php
// $user being the intended user.
// $toFollow being the one we're checking whether they follow $user or not.

$isFollowing = $user->whereHas('followers', function($q) {
  $q->where('id', $toFollow->id);
})->first();

// then you validate and do the work accordingly.
if (!$isFollowing) {
// follow
$user->followers()->save($toFollow);
}
```

Please let me know if that answers your question.

**Comment by luisalvarez** [comment]
Yes this answer my question i' ll try that i used another way but this looks a lot better

**Comment by kontoulis** [comment]
@Mulkave What you suggested executes the following statement 
```php
MATCH (user:`User`), (user)<-[rel_follows_user:FOLLOWS]-(user:`User`) WHERE id(user) = {userid} RETURN user LIMIT 1
```
This actually checks if a user($toFollow) is following himself.
The closest i came up without quering the whole connection ( $user->followers->find($toFollow)),
is this : 
```php
$user->followers()->find($toFollow->id);
```
Which produces 
```php
MATCH (user:`User`), (user)<-[rel_follows_followers:FOLLOWS]-(followers:`User`) WHERE id(user) = {iduser} and id(user) = {iduser_2} RETURN followers LIMIT 1
```
and again is of now use. 
If the part "and id(user) = {iduser_2}" was "and id(followers) = {iduser_2}" it could do the right job

**Comment by kontoulis** [comment]
@Mulkave What you suggested returns always null when the relationship is referencing the same class.
