### ISSUE TITLE
Unable to connect via HTTPS

### ISSUE THREAD

**Issue by madmanlear** [Vinelab/NeoEloquent#113]
My Neo4j server requires HTTPS, which isn't supported in this package. Could this be integrated as a configurable option?

``` php
$client = new Everyman\Neo4j\Client();
$client->getTransport()
  ->useHttps()
  ->setAuth('username', 'password');
```

**Comment by Mulkave** [comment]
@madmanlear sorry for the late reply, currently working on v2 which will surely support HTTPS. Any PRs for this are preciously welcome.
