### ISSUE TITLE
Seeder are support ? 

### ISSUE THREAD

**Issue by luisalvarez** [Vinelab/NeoEloquent#116]
how can i create a seeder to relate 2 nodes?

I want to seed my graph database, i can create seed nodes data but how seed a relation ?

**Comment by heydavid713** [comment]
Seeders can use Eloquent objects.  You can create two objects and relate them as you would in any other part of your application.

**Comment by Mulkave** [comment]
@luisalvarez have you tried what @heydavid713 suggested? If so please send feedback to whether we should close this or take action. Thanks!
