### ISSUE TITLE
Unable to delete a hasMany relationship

### ISSUE THREAD

**Issue by bramdevries** [Vinelab/NeoEloquent#120]
Some example code (running version `1.1.1`)

``` php
class Project extends Model
{
    public function releases()
    {
        return $this->hasMany(Release::class, 'CONSIST_OF');
    }
}

class Release extends Model
{

}
```

I want to delete all releases related to a project like this:

``` php
$project->releases()->delete();
```

However, this results in a: 

```
[Vinelab\NeoEloquent\QueryException]
  SyntaxException: Invalid input 'H': expected 'i/I' (line 1, column 3 (offset: 2))
  "WHERE id(project) = {idproject} DELETE releases"
```

The query generated is missing a `MATCH` statement. Any clues as to what is causing this?

The following does work:

``` php
foreach ($project->releases as $release) {
    $project->releases()->edge($release)->delete();
    $release->delete();
}
```

However this seems very verbose and the former should work imo.

**Comment by Mulkave** [comment]
Thanks for pointing that out, what version of Laravel are you running?

**Comment by Mulkave** [comment]
@bramdevries sorry for any inconvenience this has caused. This is a known issue now and will be working on solving it.

**Comment by bramdevries** [comment]
Running laravel 4.2

**Comment by bramdevries** [comment]
@Mulkave I see you've fixed this bug, but for version 2.0 (I assume this won't be compatible with Laravel 4.2). Is it possible to backport it as a new `1.1.*` release so I can pull it in?

**Comment by Mulkave** [comment]
@bramdevries this is why I'm keeping this issue open, will try porting it to `v1.2` later today, there shouldn't be any compatibility issue but still needs testing.

**Comment by bramdevries** [comment]
Can I use 1.2 on Laravel 4.2? I thought it was for Laravel 5 and higher?

**Comment by Mulkave** [comment]
Ah sorry my bad `v1.1.*` not `v1.2` :smile:
