### ISSUE TITLE
Setup authentication for the api.

### ISSUE THREAD

**Issue by xavierbarbosa** [Vinelab/NeoEloquent#128]
Currently we are using `'user' => User::first(),` to pass the user to create cases in the `CaseCreator\Http\Controllers\Api\CasesController`. This is because we need to setup proper authentication for the api. So we can correctly retrieve the user.

**Comment by heydavid713** [comment]
Are you talking about the native Laravel Authentication? Because if you are just change the file config/auth to use the eloquent driver and then change the model to your User model and it should work.

**Comment by xavierbarbosa** [comment]
Sorry, i was looking into issues and commented this here by mistake!
