### ISSUE TITLE
error with WhereNotIn

### ISSUE THREAD

**Issue by bobflay** [Vinelab/NeoEloquent#129]
I'm trying to execute this code:
![1](https://cloud.githubusercontent.com/assets/1891656/11401103/96e54af2-9399-11e5-94d9-45a1761abfd7.png)

i'm getting this exception

![2](https://cloud.githubusercontent.com/assets/1891656/11401134/b94a9cc8-9399-11e5-9e0b-bd9fa2158c45.png)

after debugging i've got the following cypher query:
![3](https://cloud.githubusercontent.com/assets/1891656/11401180/f631deda-9399-11e5-8015-4e519fba9d82.png)

It gives the same error on neo4j browser client
![4](https://cloud.githubusercontent.com/assets/1891656/11401235/397a5a50-939a-11e5-9dd0-5017d222a841.png)

After a little bit of research, i've notice that the query should be like this

![5](https://cloud.githubusercontent.com/assets/1891656/11401264/5ee534f4-939a-11e5-93bc-4178bb91732b.png)

**Comment by Mulkave** [comment]
Fixed in v1.2.11 (e25d85d0a2677692149594668e8150768ab311a3)
