### ISSUE TITLE
Command "neo4j:migrate:make" is not defined.

### ISSUE THREAD

**Issue by akanevsky** [Vinelab/NeoEloquent#140]
I installed a clean Laravel 5.1, and Neo4j is the first addition to this installation. I installed it as per the readme instructions. When I run the following command, I get an error message:

`php artisan neo4j:migrate:make create_user_label --create=User`

Here is the error message:

`←[37;41m                                                ←[39;49m`
`←[37;41m  [InvalidArgumentException]                    ←[39;49m`
`←[37;41m  Command "neo4j:migrate:make" is not defined.  ←[39;49m`
`←[37;41m  Did you mean one of these?                    ←[39;49m`
`←[37;41m      neo4j:migrate:refresh                     ←[39;49m`
`←[37;41m      neo4j:migrate                             ←[39;49m`
`←[37;41m      neo4j:migrate:reset                       ←[39;49m`
`←[37;41m      neo4j:migrate:rollback                    ←[39;49m`
`←[37;41m                                                ←[39;49m`

What am I doing wrong?

**Comment by AzeemMichael** [comment]
it should be "make:migration" not "migrate:make". They have it wrong in the docs

**Comment by akanevsky** [comment]
Thank you. That works.
