### ISSUE TITLE
Not PHP7 compatible

### ISSUE THREAD

**Issue by AzeemMichael** [Vinelab/NeoEloquent#142]
Get following error in PHP7

PHP Fatal error:  Cannot use 'Null' as class name as it is reserved in /vendor/vinelab/neo4jphp/lib/Everyman/Neo4j/Cache/Null.php on line 9

**Comment by heydavid713** [comment]
I fixed it in the underlying library that's causing the error. Will post a PR for it later today or tomorrow.

**Comment by heydavid713** [comment]
I opened a PR with my changes to the neo4jphp library. @Mulkave if you want to, I can make the changes in the Vinelab version of neo4jphp.

**Comment by Mulkave** [comment]
@heydavid713 sure! PRs are always welcome 😄

Sorry for the late reply though.

**Comment by heydavid713** [comment]
It's alright I know it was holiday season. I will fix the PR today as I thought Github used the commit hash for PRs and not the actual branch itself.
