### ISSUE TITLE
Class 'App\NeoEloquent' not found

### ISSUE THREAD

**Issue by szewang2805** [Vinelab/NeoEloquent#148]
i have followed the installation, but once i created the model, there is a error msg.
# 

Class 'App\NeoEloquent' not found

i have already add      'Vinelab\NeoEloquent\NeoEloquentServiceProvider', in the app file provider.

can you help?

<?php
namespace App;
use Vinelab\NeoEloquent\Eloquent\SoftDeletes;
use Vinelab\NeoEloquent\Eloquent\Model;
class Properties extends NeoEloquent  {

```
protected $label = 'Property'; // or array('User', 'Fan')
protected $connection = 'neo4j';
protected $fillable = ['name', 'email'];
```

}

**Comment by morilog** [comment]
You must add  `use Vinelab\NeoEloquent\Eloquent\Model as NeoEloquent` line before your `class` definition or extends your model from `Vinelab\NeoEloquent\Eloquent\Model`

**Comment by sajjadkazemi10ss** [comment]
model user:

```
namespace App;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Vinelab\NeoEloquent\Eloquent\Model as NeoEloquent;
class User extends NeoEloquent {
    protected $label = 'User'; // or array('User', 'Fan')
    protected $fillable = ['name', 'email'];
    public function phone()
    {
        return $this->hasOne('Phone');
    }
}
```
model phone

```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Vinelab\NeoEloquent\Eloquent\Model as NeoEloquent;
class Phone extends NeoEloquent {

    public function user()
    {
        return $this->belongsTo('User');
    }
}

```
error:
`Add [email] to fillable property to allow mass assignment on [App\Phone].`
