### ISSUE TITLE
Saving DateTime or Carbon objects

### ISSUE THREAD

**Issue by aymanfarhat** [Vinelab/NeoEloquent#15]
One issue I ran into is that I couldn't save a Carbon object directly to a node without formatting into a string.

Example:
```$entity = MyEntity::create([
    'name' => 'something', 
    'date_established' => Carbon::now()
]);```

Neo4j will throw an exception where it is unable to save the date object (of course)
```
  [Everyman\Neo4j\Exception]
  Unable to create node [400]:
  Headers: Array
  (
      [Content-Type] =>  application/json; charset=UTF-8; stream=true
      [Access-Control-Allow-Origin] =>  *
      [Transfer-Encoding] =>  chunked
      [Server] =>  Jetty(9.0.5.v20130815)
  )
  Body: Array
  (
      [message] => Could not set property "date_established", unsupported type: {date=2014-08-21 13:54:07.000000, timezone_type=3, timezone=UTC}
      [exception] => PropertyValueException
      [fullname] => org.neo4j.server.rest.web.PropertyValueException
      [stacktrace] => Array
          (
              [0] => org.neo4j.server.rest.domain.PropertySettingStrategy.setProperty(PropertySettingStrategy.java:141)
              [1] => org.neo4j.server.rest.domain.PropertySettingStrategy.setProperties(PropertySettingStrategy.java:88)
              [2] => org.neo4j.server.rest.web.DatabaseActions.createNode(DatabaseActions.java:214)
              [3] => org.neo4j.server.rest.web.RestfulGraphDatabase.createNode(RestfulGraphDatabase.java:238)
              [4] => java.lang.reflect.Method.invoke(Method.java:606)
              [5] => org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)
              [6] => java.lang.Thread.run(Thread.java:744)
          )
  )
```
Of course this can be circumvented by converting the Date object to string e.g. `Carbon::now()->format('y-m-d');`. 

But I am wondering if there is a way to automatically detect if a property is an instance of Carbon or DateTime and format it before insert or update without having the user do it. And vice versa when reading data into objects.

Another advantage is that  there wont be any potential issues arising from different formatting happening on dates.

Thanks!

**Comment by BrummbQ** [comment]
yes, in laravel you can throw a Carbon or PHP DateTime instance into the model. it gets converted to a database datetime type. I'm affected by the same issue in neo and right now I transform the datetime object into a unix timestamp before i put it into neo. wouldn't be of much use to store a string format anyway if you want to do some calculations.

**Comment by BrummbQ** [comment]
cool stuff, just to clarify: whats to actual data type of the datetime in neo4j if you pass in a carbon instance?

**Comment by Mulkave** [comment]
in neo4j there is no specific datetime data type to be used in storage, just a datetime string. But you may perform regular conditionals over them as you would do on a datetime field in any other database.

**Comment by aymanfarhat** [comment]
Small warning. Date string comparison works only in one date format which is `YYYY-MM-DD`, other date formats have corner cases that will not work. So if you're planning on comparing String dates in queries, make sure you stick to that format.

I think this should be included in the docs, what do you think @Mulkave ?

**Comment by Mulkave** [comment]
Interesting! Thanks @aymanfarhat for mentioning. Will make sure to have it in the docs, unless you guys submit a PR first :smile:
