### ISSUE TITLE
Edge by id

### ISSUE THREAD

**Issue by bsgrd** [Vinelab/NeoEloquent#152]
Is it possible to find an edge by it's id, and then deleting it?

**Comment by Mulkave** [comment]
Unfortunately this is not possible at the moment, can only be done using custom cypher. Will be added to the features list of v2.0. Thanks for reporting and sorry for the inconvenience.

**Comment by moeraad** [comment]
if we cannot find the edge by id, how can we update the correct edge in case we have 2 edges pointing to the same node ?

**Comment by Mulkave** [comment]
You'll have to go from the node to the edge as described in the docs here: https://github.com/Vinelab/NeoEloquent#introduction
