### ISSUE TITLE
bolt connection for Neo4j 3.0

### ISSUE THREAD

**Issue by AzeemMichael** [Vinelab/NeoEloquent#155]
I was looking at another neo4j php client at: https://github.com/graphaware/neo4j-php-client#installation-and-basic-usage and noticed they give option for bolt connection. Is it possible to do this in NeoEloquent?

**Comment by Anahkiasen** [comment]
👍  for this, would love to use the Bolt protocol but it's not evident at the moment as to how this would be done with NeoEloquent

**Comment by ryanlund** [comment]
I would also love Bolt support - potentially when I get some time after this project is complete I will look into how to add bolt support to this project as I feel it is quite important (and I love this project :D )

**Comment by Peping** [comment]
For this to be done, NeoEloquent would have to be rewritten from using `Everyman\Neo4j` to `Graphaware\Neo4j`. That's not an easy task and would potentially be a breaking release.
---------------------
While we're at it, any ideas what the 2.0.0 branch was about?
