### ISSUE TITLE
Bug with 'all' method

### ISSUE THREAD

**Issue by RomaGilyov** [Vinelab/NeoEloquent#156]
Hi)

When I do something like that

`$horse = App\Horse::all(['name'])`

I'm getting 

`Illuminate\Database\Eloquent\Collection {#850
     all: [
       App\Horse {#851
         : "Roma",
       },
     ],
   }`

collection without name property

**Comment by dgerike** [comment]
Can't reproduce in Laravel 5.6. Properties are all returned properly, with key and value.
