### ISSUE TITLE
Creation of new NeoEloquent

### ISSUE THREAD

**Issue by reshma-r-p** [Vinelab/NeoEloquent#163]
I just wanna know about how to create a new model using NeoEloquent. I created one in my models folder. And as follows,
<?php 
namespace App;
namespace App\Vinelab\Cms;
use Vinelab\NeoEloquent\Eloquent\SoftDeletes;
use Vinelab\NeoEloquent\Eloquent\Model as  NeoEloquent;

class Testposts extends NeoEloquent
{
    protected $connection = 'neo4j';
    protected $label = 'Testposts'; // or array('User', 'Fan')
    protected $fillable = ['name', 'content'];
}
But it shows the error,
FatalThrowableError in TextController.php line 38:
Class 'App\Models\Testposts' not found

**Comment by heydavid713** [comment]
You namespace should be `App\Models` not `App\Vinelab\Cms`
