### ISSUE TITLE
How to run a cypher query?

### ISSUE THREAD

**Issue by miladr0** [Vinelab/NeoEloquent#167]
Could you please show me running a cypher query using this package in laravel?

**Comment by gatewayiQ-LeadDev** [comment]
The idea is to use Eloquent in the way you normally would rather than writting Cypher queries. NeoEloquent enables you to use Laravel Eloquent with a Neo4j database (as Eloquent does not support it natively).

**Comment by Blackops404** [comment]
@gatewayiQ-LeadDev tnx, but i dont want use eloquent way, i want write pure Cypher queries to execute on neo4j database

**Comment by DeltaBravo** [comment]
Then use either the Laravel DB facade or, as I do, use
graphaware/neo4j-php-client rather than vinelab/neoeloquent.

**Comment by gatewayiQ-LeadDev** [comment]
If you want to write Cypher queries instead of using Eloquent the use either the [Laravel DB](https://laravel.com/docs/5.2/database#running-queries) facade or use
[graphaware/neo4j-php-client](https://github.com/graphaware/neo4j-php-client) rather than vinelab/neoeloquent.

**Comment by ikwattro** [comment]
@Blackops404 

@gatewayiQ-LeadDev is right

**Comment by omidmaldar** [comment]
see issue number #26 , @thylo shows a way to run Cypher queries while maintaining Neoeloquent Models.
