### ISSUE TITLE
Querying soft deleted models

### ISSUE THREAD

**Issue by Frisbeetarian** [Vinelab/NeoEloquent#169]
Is there support for withTrashed? I'm trying to access soft deleted models and I'm getting

`Call to undefined method Vinelab\NeoEloquent\Query\Builder::withTrashed()`

**Comment by KinaneD** [comment]
Yes it is supported. Which version of NE you are using?
The syntax should be something like this, where you can change `forceDelete()` to any execution methods (e.g. get, first, firstOrFail, etc.):
`$this->model->withTrashed()->where('id', '1234567')->forceDelete();`

**Comment by Frisbeetarian** [comment]
Using version 1.3.2.
Odd as I'm rooting through the query builder and can't seem to find the withTrashed method. 

I'm trying to perform the following query
Profile::withTrashed()->where('id', id)->first();
