### ISSUE TITLE
migration string field Error (Laravel 5.2)

### ISSUE THREAD

**Issue by gburu98** [Vinelab/NeoEloquent#171]
Good day,
I can not migrate a string field I printed the following error:

**[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Vinelab\NeoEloquent\Schema\Blueprint::string()** 

![my-code](https://cloud.githubusercontent.com/assets/12548796/18387521/7bc40a8e-7673-11e6-88e3-76581943b9c6.png)

**Comment by heydavid713** [comment]
Since Neo4J is schema-less, property types are unsupported, only constraints and indexes are supported.

**Comment by Gastonb98** [comment]
thanks for responding, I have to remove the strings?

**Comment by heydavid713** [comment]
Yeah, you can only use

$label->unique()	
$label->dropUnique()
$label->index()
$label->dropIndex()

After removing all the strings and enum you should be fine.

**Comment by Gastonb98** [comment]
I worked perfectly and I can do migrations, but when i look for the label Users, find me "NeoEloquent Migration" and if I make another migration, I get another "NeoEloquent Migration", that is?

**Comment by heydavid713** [comment]
I'm sorry I'm not sure I got it :/. We are fairly active on [slack](https://
*neo4j*-*users*-*slack*-invite.herokuapp.com/). Maybe we can talk a bit
more over there?
