### ISSUE TITLE
I can not create relationships

### ISSUE THREAD

**Issue by gburu98** [Vinelab/NeoEloquent#172]
When trying to save a relationship he answers: **Call to a member function phone() on null**, which it is the failure?
![person](https://cloud.githubusercontent.com/assets/12548796/18419691/eef666b8-7836-11e6-9b2f-cc79d06ffc84.png)
![route](https://cloud.githubusercontent.com/assets/12548796/18419699/f5545650-7836-11e6-9397-e20e6e5fd731.png)
![error](https://cloud.githubusercontent.com/assets/12548796/18419700/f7e3191a-7836-11e6-9269-949c97260106.png)

**Comment by Mulkave** [comment]
What version of Laravel are you using?

**Comment by gburu98** [comment]
Using Laravel 5.2.31

**Comment by Mulkave** [comment]
Can you please try `use NeoEloquent` instead of `use Vinelab\NeoEloquent\EloquentModel as NeoEloquent` in your model class.

**Comment by gburu98** [comment]
I did what you told me, but still the same error "Call to a member function save() on null
"...

**Comment by Mulkave** [comment]
Oh just noticed that your relationship method has `'Phone'` while it should be the actual class name with the full namespace. (i.e. `App\Phone`) or with a `use App\Phone` at the top you may use `Phone::class`. Can you please confirm?

**Comment by gburu98** [comment]
I leave my routes.php images and test.php (Model)
![route](https://cloud.githubusercontent.com/assets/12548796/18452741/87519064-7912-11e6-9c01-42bbfdfda5fd.png)
![model](https://cloud.githubusercontent.com/assets/12548796/18452743/8bed1e40-7912-11e6-95ac-ec061ffaec44.png)

**Comment by Mulkave** [comment]
It is not required that you `create` the phone prior to calling `$user->phone()->save($phone1);`. You may try one of the following:

```php
$prueba = Prueba::createWith(['name' => 'A'], [
  'phone' => [
    'number' => '123123',
  ]
]);

// get the phone
$phone = $prueba->phone;
```

Or if you wish to keep them separated you can use `attach` instead of `save`

```php
$prueba = Prueba::create(['name' => 'A']);

$phone = Phone::create(['number' => '987654321']);

$prueba->phone()->attach($phone);
```

**Comment by gburu98** [comment]
It worked perfectly, thank you very much to solve my problem!!!

As I locate the relationship via Neo4j browser, but I found the node "0 relationships"...
![node](https://cloud.githubusercontent.com/assets/12548796/18453191/7ebc18be-7914-11e6-888f-72376118a297.png)

**Comment by Mulkave** [comment]
@gburu98 glad it worked 😄 

That's probably the Neo4j browser saying that it is not **Displaying** any relationships, can you please try double-clicking that node?

**Comment by gburu98** [comment]
Thanks again!!!
I'm new to Neo4j, sorry for my rookie mistakes. They did an excellent job in NeoEloquent I congratulate you!
![rel](https://cloud.githubusercontent.com/assets/12548796/18453377/5bbc068e-7915-11e6-911d-1afa0cd471f8.png)
