### ISSUE TITLE
Lumen 5.3 compatibility

### ISSUE THREAD

**Issue by AzeemMichael** [Vinelab/NeoEloquent#173]
`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Laravel\Lumen\Application::booting()` when running `php artisan` command

**Comment by heydavid713** [comment]
I had a hard time configuring the database with Lumen. Should we add the steps to add Neo4J/NeoEloquent support in Lumen in the readme @Mulkave?

**Comment by heydavid713** [comment]
Hey @AzeemMichael did you try again with Lumen today?
