### ISSUE TITLE
db migrations not working in laravel 5.3 and NeoEloquent 1.4

### ISSUE THREAD

**Issue by AzeemMichael** [Vinelab/NeoEloquent#179]
1.  Getting `[BadMethodCallException]
  Method lists does not exist.` on `php artisian neo4j:migrate`

2. The command `php artisian neo4j:migrate:reset` runs into an infinite loop with a message `Nothing to rollback.`

**Comment by heydavid713** [comment]
Can you paste the stack trace for the error?

**Comment by dennisvanvalderen** [comment]
For the people that have laravel 5.3 and use NeoEloquent 1.4 or up.
There is this method called lists which is replaced by pluck.
Go to your vendor\vinelab\neoeloquent\src\Vinelab\NeoEloquent\Migrations and go to DatabaseMigrationRepository.php

 public function getRan()
    {
        return $this->model->all()->lists('migration')->toArray();
    }

Change it to

**Comment by Mulkave** [comment]
@dennisvanvalderen sorry to hear you spent all that time 😞 will fix and push

**Comment by Mulkave** [comment]
v1.4.1 has been released with the fix suggested by @dennisvanvalderen. A `composer update` should do the trick.
