### ISSUE TITLE
Neo4j | remove ID, replace UUID

### ISSUE THREAD

**Issue by gburu98** [Vinelab/NeoEloquent#181]
Good day,
I have a question with Neo4j, as I can remove the ID property and replace UUID, can you help me? Thanks for your time!

**Comment by ctorresr** [comment]
What are you trying to accomplish, neo4j ID property should never be removed.

**Comment by KinaneD** [comment]
@gburu98 Which version are you using?
In general, you should be able to do so by setting in your model class the following properties:
```
protected $primaryKey = 'uuid';
protected $incrementing = false;        // as of Laravel 5.2
```

**Comment by gburu98** [comment]
@ctorresr , I am using a generator UUID's, but it gives me error tells me that UUIDs are not supported, the problem is the length of perhaps uuid

**Comment by gburu98** [comment]
@KinaneD , I am using laravel 5.3.11, I try to apply what you told me, and see if it works

**Comment by gburu98** [comment]
look @KinaneD, probe and printed me a "fatal error"
![error](https://cloud.githubusercontent.com/assets/12548796/18952530/638ff830-8620-11e6-8070-1f2850021e38.png)

**Comment by KinaneD** [comment]
@gburu98 my bad, as the error says the `incrementing` property should be public not protected.

**Comment by gburu98** [comment]
Thanks to "public $ incrementing = false;" no longer he tells me uuid is not supported, but I have a new error:
![nuevo](https://cloud.githubusercontent.com/assets/12548796/18954215/4c820b4e-8628-11e6-8d81-42f97fa0c52e.png)

**Comment by KinaneD** [comment]
Sure! But this is a different topic. The uuid value is a string,  when in the query displayed in the error the `" "` are missing so it is being treated differently.

**Comment by gburu98** [comment]
Clear my fundamental problem was that I could not enter uuid I can now, I have to resize the string? as is done with Neo4j that amendment?

**Comment by KinaneD** [comment]
The string size is not relevant. Try casting to string what ever you assign to `$u->uuid`.

**Comment by gburu98** [comment]
I am using a translator to read the English, it was unclear what the solution to the UUID is stored would be. that the last part is not stored?
![captura de pantalla de 2016-09-29 10-14-00](https://cloud.githubusercontent.com/assets/12548796/18955363/79d4eba2-862d-11e6-8a48-1a4979c43556.png)

**Comment by KinaneD** [comment]
Try to cast to string `$uuid = (string) Uuid::generate();`.

**Comment by gburu98** [comment]
Problem solved, thanks for your support @KinaneD  !!
![bien](https://cloud.githubusercontent.com/assets/12548796/18955572/613b739e-862e-11e6-8e03-c172780e4def.png)
