### ISSUE TITLE
Migration Rollback Error

### ISSUE THREAD

**Issue by hojabbr** [Vinelab/NeoEloquent#192]
`php artisan neo4j:migrate:rollback`

**Produces:**
`Undefined index: 2016_10_22_160149_create_users_table`

My Migration file looks like this:

```
<?php

use Vinelab\NeoEloquent\Schema\Blueprint;
use Vinelab\NeoEloquent\Migrations\Migration;

class CreateUsersTable extends Migration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Neo4jSchema::label('User', function (Blueprint $label) {
            $label->unique('id');
            $label->index('name');
            $label->unique('email');
            $label->index('password');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Neo4jSchema::dropIfExists('User');
    }

}
```

But `php artisan neo4j:migrate` works correctly.

(Laravel 5.3, NeoEloquent 1.4.2)

**Comment by heydavid713** [comment]
Do you have the `migration` node? How does it look like? Also, how is your folder structure looking?

**Comment by hosseinhkj** [comment]
**This is my folder structure:**
![screenshot from 2016-10-24 10-20-28](https://cloud.githubusercontent.com/assets/3683456/19636063/a98ab07a-99d3-11e6-9d76-f8016a16296b.png)

**And this is my composer.json:**
![screenshot from 2016-10-24 10-21-03](https://cloud.githubusercontent.com/assets/3683456/19636070/b445880a-99d3-11e6-9f99-da2d7258b9b4.png)

**And I believe these are my nodes:**
![screenshot from 2016-10-24 10-22-35](https://cloud.githubusercontent.com/assets/3683456/19636089/da480dca-99d3-11e6-96fe-34a1e8d648fe.png)

**Comment by heydavid713** [comment]
You might want to delete the _users_*table* migration from the folder. Also remove that node from the DB and there should be no problem.

**Comment by Remcojansen88** [comment]
Same problem here, the problem is in the call of the default rollback

Vinelab\NeoEloquent\Console\Migrations\MigrateRollbackCommand
$this->migrator->rollback($pretend);

The rollback of elequent has this parameters
public function rollback($paths = [], array $options = []);

**Comment by javiertoledos** [comment]
Same problem here, the migration is done successfully and you can see the NeoEloquentMigration nodes in the Neo4j database, however, when you try to roll back, you get the "undefined index" error.

**Comment by Anahkiasen** [comment]
Same issue here. I can confirm @javiertoledos's fix works though in the meantime

**Comment by princeton255** [comment]
I am facing similar issue when calling rollback. Migrate works fine, but rollback throws below trace

```
./artisan neo4j:migrate:rollback

   Vinelab\NeoEloquent\QueryException  : ParameterNotFoundException: Expected parameter(s): migration, migration

  at /path-to-project/vendor/vinelab/neoeloquent/src/Connection.php: 467

Exception trace:

1   Vinelab\NeoEloquent\Connection::run("MATCH (neoEloquentMigration:`NeoEloquentMigration`) WHERE neoEloquentMigration.migration = {migration} OPTIONAL MATCH (neoEloquentMigration:`NeoEloquentMigration`)-[r]-()  WHERE neoEloquentMigration.migration = {migration} DELETE  neoEloquentMigration,r", Object(Closure))
      /path-to-project/vendor/vinelab/neoeloquent/src/Connection.php : 222
2   Vinelab\NeoEloquent\Connection::affectingStatement("MATCH (neoEloquentMigration:`NeoEloquentMigration`) WHERE neoEloquentMigration.migration = {migration} OPTIONAL MATCH (neoEloquentMigration:`NeoEloquentMigration`)-[r]-()  WHERE neoEloquentMigration.migration = {migration} DELETE  neoEloquentMigration,r")
      /path-to-project/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 435
```

I have tried @javiertoledos fix , but I am yet to get it working. 

(Laravel 5.6, NeoEloquent 1.4.6)
