### ISSUE TITLE
Feature: array properties

### ISSUE THREAD

**Issue by apopiak** [Vinelab/NeoEloquent#197]
@Mulkave @heydavid713 
I need array properties for my usage of the OGM.

I'm willing to implement them, but would like your guidance on how to do that in a compatible way (so you'll be able/want to merge my PR).
Am I correct that I would need to modify `valufy` [here](https://github.com/Vinelab/NeoEloquent/blob/1.4/src/Vinelab/NeoEloquent/Query/Grammars/Grammar.php#L134)?

**Comment by apopiak** [comment]
[This line](https://github.com/Vinelab/NeoEloquent/blob/1.4/src/Vinelab/NeoEloquent/Query/Grammars/Grammar.php#L136) makes no sense to me.
If array values are not supported it makes no sense to convert them.
The test does not have valid cypher in it, AFAIKT.
e.g. [this line](https://github.com/Vinelab/NeoEloquent/blob/1.4/tests/Vinelab/NeoEloquent/Query/GrammarTest.php#L104) would mean that I get `{someKey: 'foo', 'bar'}` if I call `prepareEntity` with something like `[ "someKey" => ["foo", "bar"] ]` which is not valid cypher, right?

**Comment by Mulkave** [comment]
@apopiak true, it is not valid Cypher, though you're looking at the right place. In the case of array parameters it would be better to use placeholders and have the driver replace them. Such as `'{someKey: {someValue}}', ['someValue' => ['foo', 'bar']]}'` using the `bindings` array in the builder.

If you need more help with this I'll be happy to support.

**Comment by apopiak** [comment]
@Mulkave
Would you be up for having a call, talking about this?
It seems like you have separate code for e.g. insert and update actions which is surprising to me.

**Comment by Mulkave** [comment]
@apopiak sure thing, please join the [Neo4j Slack channel](https://neo4j-users-slack-invite.herokuapp.com) for IM.
