### ISSUE TITLE
'Where' on multiple relations not working

### ISSUE THREAD

**Issue by legranddamien** [Vinelab/NeoEloquent#20]
Hi! 
I've found a bug when trying to get nodes with a condition on related nodes.

Here is what I'm doing : 

``` php
$query = Thing::query();

if(isset($params['author_id']))
{
    $query->whereHas('author', function($q) use ($params){
        $q->where('id', '=', intval($params['author_id']));  //THIS IS WORKING
    });
}

if(isset($params['city_id']))
{
    $query->whereHas('locations', function($q) use ($params){
        $q->whereHas('city', function($q2) use($params){
            $q2->where('id', '=', intval($params['city_id'])); //THIS IS NOT WORKING
        });
    });
}

$count = $query->count();
$list = $query->take($params['count'])->offset($params['start'])->get();
```

So if I juste have an author_id I get a list of Things, but If I've juste a city_id I get this error :

```
api.ERROR: exception 'Vinelab\NeoEloquent\QueryException' with message 'SyntaxException: city not defined (line 1, column 207)
"MATCH (thing:`Thing`), (thing)<-[rel_localize_location:LOCALIZE]-(location:`Location`) WHERE thing.deleted_at is null and location.deleted_at is null and location.city.deleted_at is null and id(city) = {idcity} RETURN count(*)" /vagrant/www/myproject/vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/Connection.php:424

Stack trace:
#0 /vagrant/www/myproject/vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/Connection.php(152): Vinelab\NeoEloquent\Connection->run('MATCH (anecdote...', Array, Object(Closure))
#1 /vagrant/www/myproject/vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/Query/Builder.php(452): Vinelab\NeoEloquent\Connection->select('MATCH (anecdote...', Array)
#2 /vagrant/www/myproject/vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/Query/Builder.php(442): Vinelab\NeoEloquent\Query\Builder->runSelect()
#3 /vagrant/www/myproject/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1336): Vinelab\NeoEloquent\Query\Builder->getFresh(Array)
#4 /vagrant/www/myproject/vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/Query/Builder.php(619): Illuminate\Database\Query\Builder->get(Array)
#5 /vagrant/www/myproject/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1713): Vinelab\NeoEloquent\Query\Builder->aggregate('count', Array)
#6 [internal function]: Illuminate\Database\Query\Builder->count()
#7 /vagrant/www/myproject/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(913): call_user_func_array(Array, Array)
#8 /vagrant/www/myproject/app/controllers/api/APIAnecdoteController.php(62): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#9 /vagrant/www/myproject/app/controllers/api/APIAnecdoteController.php(62): Vinelab\NeoEloquent\Eloquent\Builder->count()
```

**Comment by tomb10516** [comment]
@Mulkave @legranddamien 

I believe I have fixed this bug.  I added Mulkave's test to the functional tests in my branch and the test succeeds.

Please try https://github.com/tomb10516/NeoEloquent/tree/1.2.6 and let me know if it works with your application.

**Comment by tomb10516** [comment]
@Mulkave @legranddamien 

Sorry!  I take it back.  The test is green but for the wrong reasons.  When I checked the cypher output it doesn't look like what I think we should be getting for this.

Mulkave, for the above test should we try to output Cypher looking something like the following?

MATCH (permission:`Permission`) MATCH (role:`Role`)  MATCH (user:`User`) MATCH (role)-[`rel_allows`:`ALLOWS`]->(permission) MATCH (user)-[`rel_permitted_role`:`PERMITTED`]->(role) WHERE permission.alias = "read" RETURN user LIMIT 1

That is a lot of MATCH statements, but is something I know I could make fit into how the statements get compiled.

If anyone can give me better target Cypher I'll give a try to hit that target.

Thanks!

**Comment by Mulkave** [comment]
@tomb10516 your cypher can work with this:

`MATCH (permission:Permission), (role:Role), (user:User), (role)-[rel_allows:ALLOWS]->(permission), (user)-[rel_permitted_role:PERMITTED]->(role) WHERE permission.alias = "read" RETURN user LIMIT 1`

Though we might have to use the [EXISTS predicate](http://neo4j.com/docs/stable/query-predicates.html#functions-exists) with the cypher for it to work instead of simply matching?
