### ISSUE TITLE
how to delete relationship using neoEloquent?

### ISSUE THREAD

**Issue by sreesshylam** [Vinelab/NeoEloquent#201]

**Comment by KinaneD** [comment]
Take a look here: https://github.com/Vinelab/NeoEloquent#working-with-edges

**Comment by sreesshylam** [comment]
remove a single relation from group of relation

**Comment by Mulkave** [comment]
@sreesshylam can you give a code example of what you wish to achieve please.

**Comment by sreesshylam** [comment]
$ads = Ads::find(123);
$tag =$ads->tags()->get(); //get all tags relates to ads

how to remove the relation from the 'Taged' from the ads

i use this code but the tags removed form the corresponding node 		
foreach ($tag as $key => $value) {
	$value->delete();
}

i need only relation removed from Ads

**Comment by ctorresr** [comment]
`        foreach ($ads->tags()->edges() as $relation) {
                $relation->delete();
            }
`

**Comment by sreesshylam** [comment]
i have also one dbt how to convert cypher query (MATCH p=(Ads)-[r:TAGS]->(Tags)<-[r1:INTERESTED]-(User) RETURN p) to corresponding  NeoEloquent

**Comment by ctorresr** [comment]
@sreesshylam You can also use raw cypher for more complicated query's. Create a stored procedures class and give it a try.
