### ISSUE TITLE
I am un able to make model that is connected with neo4j

### ISSUE THREAD

**Issue by MuddassirPasta** [Vinelab/NeoEloquent#202]
I was making model as

namespace app;

use Vinelab\NeoEloquent\Eloquent\Model;

class Product extends NeoEloquent
{
    
}

FatalErrorException in Product.php line 7:
Class 'App\NeoEloquent' not found

**Comment by AzeemMichael** [comment]
Try one of these.
Solution 1: `use Vinelab\NeoEloquent\Eloquent\Model as NeoEloquent`; or
Solution 2: `class Product extends Model`

**Comment by freitasbruno** [comment]
Can also try simply adding a backslash before NeoEloquent
`class Product extends \NeoEloquent`

**Comment by Mulkave** [comment]
The solutions provided by @AzeemMichael and @freitasbruno works very well.

Also, you may add the service provider `'Vinelab\NeoEloquent\NeoEloquentServiceProvider',` to the `providers` array in `config/app.php` you should be able to do something like:

```php
namespace app;

use NeoEloquent;

class Product extends NeoEloquent
{

}
```
