### ISSUE TITLE
[1.5-dev] Laravel 5.3 compability

### ISSUE THREAD

**Issue by geminixxl** [Vinelab/NeoEloquent#205]
I wanted to test version 1.5-dev but this did not work. It seems as if the version is not compatible with Laravel 5.3.

For example I get the following error when using `artisan db:seed`:

`Declaration of Vinelab\NeoEloquent\Frameworks\Laravel\Connection::transaction(Vinelab\NeoEloquent\Frameworks\Laravel\Closure $callback, $attempts = 1) must be compatible with Illuminate\Database\ConnectionInterface::transaction(Closure $callback, $attempts = 1)`

Also the method `getMigrations` is missing in the class `Vinelab\NeoEloquent\Migrations\DatabaseMigrationRepository`.

Additional: after I installed 1.5-dev `{{ csrf_field() }}` doesn't work anymore. It prints the html entities instead of <,>, ...
Maybe there are also more problems.

Is it possible to clarify the compatibility with Laravel in the version number? For example with a version schema like a.b.c.d where a is the main NeoEloquent version, b.c the Laravel version and d a number for bug fixes of NeoEloquent?

**Comment by Anahkiasen** [comment]
Same issue here, I want to use UUIDs with NeoEloquent but from what I understand in order to do this I need 1.5 which is unavailable for 5.3 at the moment

**Comment by geminixxl** [comment]
@KinaneD Any updates?

**Comment by Mulkave** [comment]
@geminixxl can you confirm if merging both PRs makes this issue safe to close?

**Comment by geminixxl** [comment]
Sorry for the late answer but I haven't much time at the moment.

There are many more errors. For example: Why do classes such as `Vinelab\NeoEloquent\Query\Grammars\Grammar` or `Vinelab\NeoEloquent\Query\Builder` not extend `Illuminate\Database\Query\Grammars\Grammar` or  `Illuminate\Database\Query\Builder` as they do it in 1.4, 2.0.0-alpha and 2.0.0-alpha-plus?

When I have time, I will create new PRs ;) Maybe you can also take a look at these problems.
