### ISSUE TITLE
Error When Using Debugbar

### ISSUE THREAD

**Issue by Frisbeetarian** [Vinelab/NeoEloquent#207]
Trying to use the following package:
https://github.com/barryvdh/laravel-debugbar

And I'm getting a 
`"FatalThrowableError in QueryCollector.php line 109: Call to a member function quote() on null"`
on every page hit. 

Issue has been discussed as it relates to Neoeloquent on the Debugbar repo: https://github.com/barryvdh/laravel-debugbar/issues/306

**Comment by Mulkave** [comment]
Quoting this answer: https://github.com/barryvdh/laravel-debugbar/issues/306#issuecomment-82631504

`Either it should check if getPdo() returns something and if so call ->quote() or use a generic quote method OR ignore/drop the query altogether (so no query logging for custom Connection).`

`getPdo()` isn't used in NE, not sure about the compatibility with Debugbar. If you've used it I'd love to merge a PR implementing this compatibility.
