### ISSUE TITLE
Specifying A Select Clause

### ISSUE THREAD

**Issue by hsalem7** [Vinelab/NeoEloquent#208]
Hello guys,

I am using NeoEloquent v- 1.3 with Laravel 5.3

I was trying 
`User::select('email as user_email')->get()->toArray();`

but the result was: 
```
[
    'email as user_email' => 'h.salem7788@gmail.com'
]
```

expected results:

```
[
    'user_email' => 'h.salem7788@gmail.com'
]
```

----

also, another problem was when I was trying 
`User::get(['email'])->toArray();`
or
`User::all(['email'])->toArray()`

the result is: 

```
[
    '' => 'h.salem7788@gmail.com'
]
```

expected 
```
[
    'email' => 'h.salem7788@gmail.com'
]
```

**Comment by Mulkave** [comment]
Can you please confirm whether this is still valid? Updates have been pushed since.
