### ISSUE TITLE
Do not return Node IDs

### ISSUE THREAD

**Issue by guivazcabral** [Vinelab/NeoEloquent#216]
Hi. Is it possible to not return Neo4j's internal ID when returning the model? 

For example, i'm fetching Authors:

`Author::take($limit)->orderBy($orderBy, $sort)->skip($skip)->get();`

and the response is 

    [{
     "lastName": "Alegre",
    "firstName": "Manuel",
    "uuid": "83380596c47911e680dc0242ef3a492b",
    "id": 360
    }]

and I don't need the "id" property. Is there any way I can *not* return the id?

**Comment by Mulkave** [comment]
You may use the `$hidden` property in the model to specify the fields that you would like to hide.

```php
class MyModel extends Model
{
    protected $hidden = [];
}
```
