### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by BillCao1997** [Vinelab/NeoEloquent#221]
As new version of Laravel was released, composer wont let me install the v1.4.2. Thanks!

**Comment by Mulkave** [comment]
This needs upgrading the required illuminate packages in `composer.json` and an update in the service provider. Will get back to this later. Or if you were able to work it out, appreciate a PR 😄

**Comment by mihaizzza** [comment]
When do you appreciate an update for Laravel 5.4?

**Comment by jarosenthal** [comment]
Is there any timeline for an update....? @Mulkave

**Comment by alecoletti** [comment]
Any updates on this matter?

**Comment by heydavid713** [comment]
What I usually do is update the `composer.json` file and then debug the compatibility issues. They are usually just namespace changes or class changes.

**Comment by marshy2346** [comment]
5.4 support is in

**Comment by alexislefebvre** [comment]
According to the [1.4.3 release message](https://github.com/Vinelab/NeoEloquent/releases/tag/v1.4.3), Laravel 5.4 is supported.
