### ISSUE TITLE
Querying the relation of a non-persisted model shouldn't return all of that label

### ISSUE THREAD

**Issue by Anahkiasen** [Vinelab/NeoEloquent#225]
Imagine I have an User model that can have multiple roles defined as such:

```php
public function roles()
{
    return $this->hasMany(Role::class, 'IS');
}
```

Now if I get an User model and fetch its roles, all good:

```php
>>>Acme\Entities\Models\User::first()->roles->count()
=> 1
```

But if I do this on a new model, it will return _all existing roles_:

```php
>>> (new Acme\Entities\Models\User)->roles->count()
=> 16
```

Instead of nothing like it does with normal Eloquent, example on another project of mine that does not use neo4j:

```php
>>> Acme\Entities\Models\User::first()->groups->count()
=> 1
>>> (new Acme\Entities\Models\User)->groups->count()
=> 0
```

I've tripped on this a good bunch of times, mostly when writing upsert logic dealing with models that may or may not exist, some cases causing quite the headache so, thought I'd see if this could maybe be changed to behave like SQL Eloquent does.

**Comment by Mulkave** [comment]
What is the intended behaviour that you're expecting from this?

```php
>>>Acme\Entities\Models\User::first()->roles->count()
=> 1
```

**Comment by Anahkiasen** [comment]
It should return 0 like it does in Eloquent in my opinion
