### ISSUE TITLE
Relations have wrong direction

### ISSUE THREAD

**Issue by emredoganm** [Vinelab/NeoEloquent#227]
In my `Categories` model, I declared relationships like this:

```php
    public function children(){
      return $this->hasMany("Models\Categories", "IS_CHILD_OF");
    }

    public function parent(){
      return $this->belongsTo("Models\Categories", "IS_CHILD_OF");
    }
```

but when I run this:

```php
    $programming = Categories::whereName("programming")->first();
    $neo4j = $programming->children()->save(Categories::create([
        "name" => "neo4j"
   ]));
```

relationship direction has wrong direction.
![image](https://cloud.githubusercontent.com/assets/6019496/24336706/7cc10dcc-129c-11e7-8674-c192a90a0e83.png)

**Comment by emredoganm** [comment]
Also `Category::has('children')->get()` returns an empty collection. Maybe this problem related to the problem above... If not I can open a new issue.

**Comment by KinaneD** [comment]
Hi @emredoganm In your `categories` model you declared two relationships to the same `categories` model. Is this intended?

**Comment by emredoganm** [comment]
Is this un-solicited status? A category has a parent category and children categories. How can I declare?

**Comment by Mulkave** [comment]
@emredoganm there doesn't seem to be anything wrong in the sample you posted. `hasMany` means `programming -[IS_CHILD_OF]-> children` declared with a `hasMany` relationship. While `programming <-[IS_CHILD_OF]- parent` declared with a `belongsTo`. All as described in the docs https://github.com/vinelab/neoeloquent#one-to-many

Is there anything that you find confusing about this?

**Comment by emredoganm** [comment]
I think I should change my relation name to "HAS_CHILD". It is more smarter :-D

**Comment by thanosalexander** [comment]
i have to reopen :smiley: 
When i use createWith (with parent relationship inside), it is displayed correctly in graph preview.
But when i use  ``` $model->parent()->associate($parent)->save() ``` direction is displayed as edgeout..
