### ISSUE TITLE
Conflict on Same Model

### ISSUE THREAD

**Issue by emredoganm** [Vinelab/NeoEloquent#228]
As mentioned in documentation [here](https://github.com/Vinelab/NeoEloquent#many-to-many), I've created a `User` model and `followers`relationship like this:

```php
  public function followers()
  {
    return $this->belongsToMany(User::class, "FOLLOWS");
  }
```
But when I debug this query:
```php
dd(User::has("followers")->get());
```
and echoing out `$query` from `run() function in Vinelab\Eloquent\Connection` the result is:
```cypher
MATCH (user:`User`), (user)<-[rel_follows_user:FOLLOWS]-(user:`User`) WITH user, count(user) AS user_count WHERE user_count >= 1 RETURN user
```

Target node is named as `user` and source node is named as `user` and it conflicts in Cypher and returns an empty collection. I think it is a bug. How can we solve this?

**Comment by emredoganm** [comment]
I have created a PR for this problem: #229.

This PR will generate a cypher query like this with situtation above:

```php
dd(User::has("followers")->get());
```

Cypher query:
`MATCH (user:`User`), (user)<-[rel_follows_user:FOLLOWS]-(related_user:`User`) WITH user, count(related_user) AS user_count WHERE user_count >= 1 RETURN user
`

**Comment by Mulkave** [comment]
Please confirm the fix of this in your PR to close.

**Comment by k98kurz** [comment]
@Mulkave is there some reason his suggested fix was not implemented? It is kind of embarrassing for your example code to not work.

**Comment by Mulkave** [comment]
@k98kurz this would require further testing and spectating to figure out whether it has any side effects on mapping or hydrating models, since it relies on these variables to figure out the properties.

Not sure if @emredoganm is still up for the fix?
