### ISSUE TITLE
Add spatial plugin support

### ISSUE THREAD

**Issue by eIiam** [Vinelab/NeoEloquent#23]
Are you planning to add it like Neography for ruby ?

https://github.com/maxdemarzi/neography

https://github.com/neo4j-contrib/spatial

Thanks!

**Comment by tusharvikky** [comment]
Any updates on spatial. I am looking for the exact same thing!

**Comment by Mulkave** [comment]
@tusharvikky Honestly I've never used Spatial myself, would love some insight on what is expected from NeoEloquent in that regard.
