### ISSUE TITLE
Builder needs to have a 'hasNot' function

### ISSUE THREAD

**Issue by emredoganm** [Vinelab/NeoEloquent#230]
This query doesnt work with Neo4j 3.0.1
`User::has("followers","<",1)->get()`

I am using Laravel 5.3.31 and NeoEloquent 1.4

I tried to change source code but could not do it. If we have a `hasNot()` function which generates this cypher query:

`MATCH (parentNodeOf:User) WHERE NOT (parentNodeOf)<-[:FOLLOWS]-(:User) return parentNodeOf`

**Comment by Mulkave** [comment]
Compatibility has been implemented long ago, if this is still valid please re-open. Sorry for the late reply.
