### ISSUE TITLE
Get node or relationship by id - bad practice

### ISSUE THREAD

**Issue by m0067** [Vinelab/NeoEloquent#233]
Hello, I have some issue. Follow [docs of neo4j](https://neo4j.com/docs/developer-manual/current/cypher/clauses/match/#get-node-rel-by-id), it is not good use 
`
MATCH (user:User), (followers:User)
WHERE id(user) = 1 AND id(followers) = 2
CREATE (followers)-[:FOLLOWS]->(user)
RETURN followers;
`
it should be better use uuid of application for future consistency
`
MATCH (user:User), (followers:User)
WHERE user.uuid = 'unique' AND followers.uuid = 'unique2'
CREATE (followers)-[:FOLLOWS]->(user)
RETURN followers;`
`
So how can I use second variant?

**Comment by Mulkave** [comment]
Thanks for the suggestion! will look into it in the next release.
