### ISSUE TITLE
Use this with Laravel 5.4

### ISSUE THREAD

**Issue by yavand** [Vinelab/NeoEloquent#234]
Hello, I'm new in Laravel and i want to use NeoEloquent with Laravel 5.4, but instruction is available for Laravel 5.3 and below. 
Please help me, step by step, how to use NeoEloquent with Laravel 5.4. It's very neccessary for me.
Thank's a lot.

**Comment by AzeemMichael** [comment]
@yavand Laravel 5.4 is not yet supported. See #221

**Comment by yavand** [comment]
So How can I Compatible this package with Laravel 5.4?

**Comment by AzeemMichael** [comment]
@yavand That's the point, you can't until they resolve that issue. You can follow their progress at #221 . From my experience it takes a while to get support for newer versions of Laravel. Also, fyi neo4j 3.2 also is not supported yet. See #232 .

**Comment by Mulkave** [comment]
Installation is possible, please see https://github.com/vinelab/neoeloquent#54

Can be done with `composer require vinelab/neoeloquent=1.4.3`
