### ISSUE TITLE
chunk confusing child's Label with parent label

### ISSUE THREAD

**Issue by jasekiw** [Vinelab/NeoEloquent#237]
When chunking through results and then grabbing a list of nodes from each node it confuses which label it is using.
```
TemplateForm::orderBy('created_at', 'ASC')->chunk(2, function(Collection $templates)  {
    $templates->each(function($template)  {
          $pages = $template->pages;
     });
});
```
Throws error
```
  [Vinelab\NeoEloquent\QueryException]                                         
  SyntaxException: Variable `pages` not defined (line 1, column 43 (offset: 4  
  2))                                                                          
  "MATCH (templateForm:`TemplateForm`) WHERE pages.deleted_at is null RETURN   
  * ORDER BY pages.created_at ASC SKIP 2 LIMIT 2" 

```

The query works fine until I access the children.

This is very strange and seems like a reference issue.
if I take out the chunk and replace it with a standard each everything works as expected. I cannot however pull all of these at once.

**Comment by Mulkave** [comment]
Not aware of `chunk`'s functionality, can you please elaborate on its usage/need?

**Comment by jasekiw** [comment]
https://laravel.com/docs/5.4/queries
Scroll down until you see "Chunking Results".

**Comment by Mulkave** [comment]
Oh that! No tests exist for that atm so can't tell about this feature's compatibility. If you have the time for a PR I'd love to look at and merge. Thanks for reporting.
