### ISSUE TITLE
Laravel 5.5 LTS support

### ISSUE THREAD

**Issue by Gaba93** [Vinelab/NeoEloquent#239]
Will you support Laravel 5.5?

**Comment by JVTT** [comment]
Did you ask in their public Slack channel?

**Comment by andrewdalpino** [comment]
Let's get this baby on 5.5

Does anyone have a good estimate as to what it would take?

**Comment by AerysL** [comment]
Laravel 5.5 contains a number of changes which require changes to the library. The full listing of breaking changes is available [here](https://laravel.com/docs/5.5/upgrade). It appears to me the following changes need to be made

- [ ] Updating Dependencies
   - PHP to 7.0
   - Illuminate/* to 5.5.*
   -  phpunit to ~.60
    - Requires a change to TestCase.php changing the underscores  in the phpunit use statement to backslashes
- [ ] Update the belongsToMany method signature
    - Likely rework the logic, as the names are now provided
- [ ] Update relationship create methods
  -  BelongsToMany, HasOneOrMany, and MorphOnOrMany signatures have changed
 - [ ] Soft Deleted models exists property now remains true, so update SimpleCRUDTest to reflect this
