### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by zmorris** [Vinelab/NeoEloquent#242]
Hi, I think perhaps the Camo links are down in the README.md?

HyperEdges:

https://camo.githubusercontent.com/fb17a22867368f6dbc7fbc513cfceaf778e57f00/68747470733a2f2f676f6f676c6564726976652e636f6d2f686f73742f30427a6e7a5a326c42625430634c573959636a4e6c646c4a6b6358632f4879706572456467652e706e67

CreateWith:

https://camo.githubusercontent.com/59cbdce535fe860ceb8c04576db46d9281f91c04/68747470733a2f2f676f6f676c6564726976652e636f6d2f686f73742f30427a6e7a5a326c42625430634c573959636a4e6c646c4a6b6358632f637265617465576974682d707265766965772e64622e706e67

**Comment by alexislefebvre** [comment]
And the link to `HyperEdges` is broken in another part of the documentation: https://github.com/Vinelab/NeoEloquent/blob/acff98c1b325e6333924a8f31526682a0e235a9b/README.md#working-with-edges
