### ISSUE TITLE
Laravel's auth register/login not working for Laravel 5.4 and neoeloquent 1.4.3

### ISSUE THREAD

**Issue by bryanchapel** [Vinelab/NeoEloquent#244]
I keep getting this error on register even though the node is actually successfully being created in the database:

(1/1) FatalThrowableErrorCall to a member function lastInsertId() on null
--
in Processor.php (line 34)
at Processor->processInsertGetId(object(Builder), 'CREATE (:`users` { name: \'lkasjdfklajsfkljasklfdjklsjfkl\', email: \'babsjdbfakjsbdf@hotmasdfdfil.com\', password: \'$2y$10$uOgn/K/3GHv0WbCQVEFqJu/QKasPbQ1qTWoqxpWKeUhH3MVVx8bB2\', updated_at: \'2017-08-19 06:54:59\', created_at: \'2017-08-19 06:54:59\'})', array('lkasjdfklajsfkljasklfdjklsjfkl', 'babsjdbfakjsbdf@hotmasdfdfil.com', '$2y$10$uOgn/K/3GHv0WbCQVEFqJu/QKasPbQ1qTWoqxpWKeUhH3MVVx8bB2', '2017-08-19 06:54:59', '2017-08-19 06:54:59'), 'id')in Builder.php (line 2139)

And when I try to login I get: 

(1/1) ErrorExceptionUndefined property: Illuminate\Database\Query\Builder::$matches
--
in CypherGrammar.php (line 99)
at HandleExceptions->handleError(8, 'Undefined property: Illuminate\\Database\\Query\\Builder::$matches', '/Library/WebServer/Documents/neotest/vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/Query/Grammars/CypherGrammar.php', 99, array('query' => object(Builder), 'components' => array('matches', 'from', 'with', 'wheres', 'unions', 'columns', 'orders', 'offset', 'limit'), 'component' => 'matches', 'cypher' => ''))in CypherGrammar.php (line 99)

Does anyone have any suggestions about what I can do here? Should I be changing versions? I've tried several combinations of laravel 5.3.*-5.4.* paired with neoeloquent 1.4.* and I just cannot get anything working right.

**Comment by bluerain75** [comment]
+1

**Comment by djkevino** [comment]
Also for Neoeloquent 1.4.4 and Laravel 5
