### ISSUE TITLE
Neo4J Laravel Migration Creates DummyTable

### ISSUE THREAD

**Issue by sanjade** [Vinelab/NeoEloquent#245]
When i make migration using `php artisan neo4j:make create_user_label --create=User` it creates dummy table with Schema but i want is it to create Neo4J Schema instead of Dummy Table. Please Help me.
Makes this:
````<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class DummyClass extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('DummyTable', function (Blueprint $table) {
            //
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('DummyTable', function (Blueprint $table) {
            //
        });
    }
}
````
Want this:
````
use Vinelab\NeoEloquent\Schema\Blueprint;
use Vinelab\NeoEloquent\Migrations\Migration;
class CreateTestpostsTable extends Migration {
/**
 * Run the migrations.
 *
 * @return void
 */
public function up()
{
    Neo4jSchema::label('Testposts', function(Blueprint $label)
    {
         //
    });
}
/**
 * Reverse the migrations.
 *
 * @return void
 */
public function down()
{
    Neo4jSchema::drop('Testposts');   
}

}
````

Please Help

**Comment by JVTT** [comment]
I have also noticed this happening when I run `neo4j:make:migration create_label_name`. Seems pretty bad. Also, could you reformat the issue to make it look more like this? (Use 4 spaces instead of the backticks.)

    <?php
    
    use Illuminate\Support\Facades\Schema;
    use Illuminate\Database\Schema\Blueprint;
    use Illuminate\Database\Migrations\Migration;
    //etc

**Comment by Mulkave** [comment]
Not sure if this would still be valid after https://github.com/Vinelab/NeoEloquent/pull/255?
