### ISSUE TITLE
Neo4j Lumen :  Binding param in Request with : wraped where (whereNested) [BUG]

### ISSUE THREAD

**Issue by BenjaminSpb** [Vinelab/NeoEloquent#247]
When you want wrap "where" in request binding don't work fine.

Example : 
- If want do this request  
`MATCH (campaign:Campaign) WHERE campaign.name = "a" or (campaign.name= "b" and campaign.size = 4)`

- I use this to add "where" on my query :
```
 $query->where("name", "=", "a");
 $query->orWhere(function ($query)  {
            $query->where("name", "=", "b");
            $query->where("size", "=", 4);
 });
```

=> In the log of lumen i can see the binding of my first "where" was  remove :
```
lumen.INFO: MATCH (campaign:Campaign) WHERE campaign.name = {name} or (campaign.name = {name} and campaign.size = {size}) RETURN count(*)  
 lumen.INFO: Array
(
    [name] => b
    [size] => 4
)
 
```
PS :  normaly we need to have  {name_1} and {name_2} not only {name}

Have you a solution to resolve for this Bug ?

Thanks,

**Comment by Mulkave** [comment]
Can you please try chaining two `orWhere` clauses?

```php
$query->where("name", "=", "a");
$query->orWhere(function ($query)  {
            $query->where("name", "=", "b");
            $query->orWhere("size", "=", 4);
 });
```

Or with this instead:

```
$query->where("name", "=", "a");
$query->orWhere("name", "=", "b");
$query->orWhere("size", "=", 4);
```
