### ISSUE TITLE
Can i do this? `with` with a `where` condition?

### ISSUE THREAD

**Issue by oberoivarun** [Vinelab/NeoEloquent#260]
On Laravel 5.3 and the appropriate NeoEloquent.

I'd like to run the following query:

```
Card::with(['owner','coupons' => function($q) {
            $q->where('status', '!=', 'used')->where('expiry_date', '>', Carbon::now());
        }])->find($id);
```

It's not working right. I do have coupons in the DB which qualify the inner conditions. Is there a way to do this in NeoEloquent. As this is possible in basic  #Laravel.

If not, then i guess this would be a feature request.

**Comment by Mulkave** [comment]
The only test for such feature that exists is this one: https://github.com/Vinelab/NeoEloquent/blob/1.4/tests/functional/QueryingRelationsTest.php#L569

Would that meet your requirements? Or is it something else?

**Comment by oberoivarun** [comment]
Yes this works. But i think the problem is with the `!=` operator. 

I tried a simple query:

`Job::count()` return `60`

`Job::where('status','Cancel')->count()` returns say `10`

`Job::where('status','!=','Cancel')->count();` returns `0`

It should return 50. This is probably why the code in my first post is not working.

**Comment by oberoivarun** [comment]
@Mulkave Any ideas?

**Comment by Mulkave** [comment]
Can't think of anything, honestly. @KinaneD thoughts?

**Comment by oberoivarun** [comment]
@Mulkave Can you confirm that this issue exists though? If not, i should take a harder look at my repo, or create a new one and check again.

**Comment by Mulkave** [comment]
Can you please try `Job::where('status','<>','Cancel')->count();` i'm suspecting the operator has something to do with this.

**Comment by oberoivarun** [comment]
Yes! `Job::where('status','<>','Cancel')->count();` returns `10`.

**Comment by Mulkave** [comment]
Great @oberoivarun! Should we close then?

**Comment by oberoivarun** [comment]
Yeah... Wouldn't this be a bug though?

**Comment by Mulkave** [comment]
@oberoivarun not really: https://neo4j.com/docs/developer-manual/current/cypher/syntax/operators/#query-operators-comparison
