### ISSUE TITLE
BadMethodCallException: undefined method Builder::getArrayableAttributes()

### ISSUE THREAD

**Issue by DeltaBravo** [Vinelab/NeoEloquent#261]
>  BadMethodCallException
> Call to undefined method Vinelab\NeoEloquent\Query\Builder::getArrayableAttributes()

https://laravel.com/api/5.5/Illuminate/Database/Eloquent/Concerns/HasAttributes.html#method_getArrayableAttributes

laravel/framework        v5.5.25
vinelab/neoeloquent    v1.4.4

Worked with Laravel 5.3 and NeoEloquent 1.4.3 iirc.

**Comment by Mulkave** [comment]
Can you please open a Pull Request with your fix?

**Comment by DeltaBravo** [comment]
I do not have a fix. My workaround was to use `getAttributes()` instead as it met my needs but it is not a drop-in replacement.

The issue is really that none of the 'HasAttributes' trait methods are available because ::find() is not returning a model but instead a Builder object. 

This is all just a bit over my head so I cannot help beyond reporting and answering questions.

**Comment by Mulkave** [comment]
@DeltaBravo cool, thanks for reporting!
