### ISSUE TITLE
Problem with nested WhereHas

### ISSUE THREAD

**Issue by dimitriSpb** [Vinelab/NeoEloquent#271]
Hi,

I can't use nested whereHas with queryBuilder because it use only my first whereHas.

This is example : 
`
$collection = Lead::whereHas('guest', function($q){
            $q->whereHas('candidature', function($c){
                $c->whereHas('campaign',function($camp){
                    $camp->where('id_mdb',4);
                });
            });
        })->get();
`

Query result : 
`MATCH (lead:`Lead`), (lead)<-[`rel_has_generated_guest`:`has_generated`]-(guest:`Guest`) WHERE guest.candidature.campaign.id_mdb = 4 and lead.deleted_at is null RETURN lead  
`
As you can see only first whereHas and where clause is bad : guest.candidature.campaign.id_mdb = 4

I do something bad ? You have a solution ? Or it's bug ?

Lumen (5.4.7) (Laravel Components 5.4.*)
"vinelab/neoeloquent": "1.4.*",

**Comment by romainSaya** [comment]
Yes me too, i have the same problem with nested wherehas. Just the first one is used. Any solutions ? Thank you
