### ISSUE TITLE
ParameterNotFoundException: Expected a parameter named email

### ISSUE THREAD

**Issue by willneumann** [Vinelab/NeoEloquent#272]
I'm getting a Vinelab NeoEloquent QueryException: "**ParameterNotFoundException: Expected a parameter named email**" when I'm doing the following:

1. After opening the password reset link from the email, entering email address and new password and clicking "Reset Password".
2. Also getting it when trying to request a password reset and at least one password reset already exists in the database for any user/email address.

Looks like it's having some issue looking up the record on the password_resets node for some reason. I'm on Laravel 5.5 with Neo4J 3.3.1, with the built-in Laravel auth scaffolding. Other auth functions like register/login/logoff work fine.

This started to happen after I switched my User Model to NeoEloquent. My User model currently looks like this:

    namespace App;

    use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
    use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
    use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
    use Illuminate\Auth\Authenticatable;
    use Illuminate\Auth\Passwords\CanResetPassword;
    use Illuminate\Foundation\Auth\Access\Authorizable;

    class User extends \NeoEloquent implements 
        AuthenticatableContract,
        AuthorizableContract,
        CanResetPasswordContract
    {
        use Authenticatable, CanResetPassword, Authorizable;

        protected $label = 'User'; 

        protected $fillable = [
            'name', 'email', 'password'
        ];

        protected $hidden = [
            'password', 'remember_token',
        ];
    }

I found that if I comment out "return $this->email;" in the getEmailForPasswordReset() function of Illuminate\Auth\Passwords\CanResetPassword, the issue goes away, but then it allows the user to reset any account/email address with a valid reset token (which is obviously a security issue).

Not sure where to go from here. Really appreciate your help.

**Comment by willneumann** [comment]
This no issue with Laravel 5.3 and 5.4. I have switched back to 5.4 for the time being.

**Comment by devahmad92** [comment]
Yes its Laravel 5.5 issue 
I'm facing the same issue here
