### ISSUE TITLE
No relationship start node specified

### ISSUE THREAD

**Issue by fzhan** [Vinelab/NeoEloquent#282]
1. laravel 5.5.*
2. neoeloquent ^1.4

$brand = new Brand ([...]);
$brand->save(); // ok
$series = new Series ([...]);
$brand->series()->save($series);

No relationship start node specified {"exception":"[object] (Everyman\\Neo4j\\Exception(code: 0): No relationship start node specified at vendor/heydavid713/neo4jphp/lib/Everyman/Neo4j/Command/CreateRelationship.php:77

**Comment by KonradMil** [comment]
Have you tried approach like:
$series = new Series ([...]);
$series->save();
$brans->series()->attach($series);

We have been using this package quite extensively and we encountered several occasion that simple switching approach was enough to fix issue.

**Comment by fzhan** [comment]
@KonradMil will give it a go, thanks!
