### ISSUE TITLE
Undefined property: Illuminate\Database\Query\Builder::$matches

### ISSUE THREAD

**Issue by juliustm** [Vinelab/NeoEloquent#283]
> Undefined property: Illuminate\Database\Query\Builder::$matches

I have done all the necessary configurations but I get the error above each time I try to Authenticate a user ( Passport using OAuth 2 )

Laravel : 5.4
NeoElquent : 1.4.3

**Comment by asifnadaf** [comment]
Hi,

I am using Laravel Authentication. 

I am also facing the same issue with
Laravel: 5.6
NeoEloquent: 1.4.7

/var/www/html/plusconnect.tk/public_html/vendor/vinelab/neoeloquent/src/Query/Grammars/CypherGrammar.php


protected function compileComponent(Builder $query, $components, $component)
    {
        $cypher = '';
 
        // Let's make sure this is a proprietary component that we support
        if ( ! in_array($component, $components))
        {
            throw new InvalidCypherGrammarComponentException($component);
        }
 
        // To compile the query, we'll spin through each component of the query and
        // see if that component exists. If it does we'll just call the compiler
        // function for the component which is responsible for making the Cypher.
        if ( ! is_null($query->$component))
        {
            $method = 'compile'.ucfirst($component);
 
            $cypher = $this->$method($query, $query->$component);
        }
 
        return $cypher;
    }
 
    /**
     * Compile the MATCH for a query with relationships.
     *
     * @param  \Illuminate\Database\Query\Builder $query
     * @param  array  $matches
     * @return string
     */
    public function compileMatches(Builder $query, $matches)
    {
        if ( ! is_array($matches) || empty($matches)) return '';


"Undefined property: Illuminate\Database\Query\Builder::$matches"


Thanks
