### ISSUE TITLE
Follow Laravel's versioning pattern.

### ISSUE THREAD

**Issue by oberoivarun** [Vinelab/NeoEloquent#289]
Rather than NeoEloquent 1.4.6 for Laravel 5.6, it'll be better to have NeoEloquent 5.6 for Laravel 5.6

It's like in Angular, all supporting packages version up with the Angular Core package.

**Comment by berteltorp** [comment]
Laravel and its other first-party packages now follow Semantic Versioning [ref](https://laravel.com/docs/7.x/releases#versioning-scheme) - I think it would make more sense if we did that as well.

I expect the next major release to be centered around replacing the unmaintained driver (the heydavid713/neo4jphp dependency) which warrant's a new major version (eg. 2.0).
