### ISSUE TITLE
Get all label names of a node

### ISSUE THREAD

**Issue by aymanfarhat** [Vinelab/NeoEloquent#29]
Hey, it would be extremely useful if there was a function for checking out all the labels for a given node. For now using `$myModelInstance->getTable()` or `$myModelInstance->getDefaultNodeLabel()` would only return the first label for that node.
## UPDATE:

It turned out this is specific to a case I have, occurring for nodes bearing multiple labels. Here is a detailed example.

I have two labels: Startup, Organization and Profile. I have the following node classes:

`class Startup extends NeoEloquent {
    protected $label = ['Startup', 'Profile'];
}`

`class Organization extends NeoEloquent {
    protected $label = ['Organization', 'Profile'];
}`

`class Startup extends NeoEloquent {
    protected $label = ['Profile'];
}`

There could be many other node classes having Profile as their label too. What I am trying to do is query the Profile model by a common attribute between the other profiles, get the result and infer the type of node from that. Example: `Profile::where('slug','=','something')->first();`

The above example would query all nodes that bear the label Profile regardless of the rest of their labels (which is exactly what I want) but of course the object type of the returned result is Profile. Calling `getTable()` on the result would simply return `['Profile']` despite the match being on a node that has multiple labels such as Startup or Organization.

 Let me know if my idea is clear enough, would love to hear your thoughts about this. In case it can be a possible feature or there is a good way I can go around this issue.

**Comment by sameer-shelavale** [comment]
I like concept of @aymanfarhat that $table should be the main labels defining the model. and $label should store all actual labels.

**Comment by sameer-shelavale** [comment]
I will add this method, will it be fine if we name it getAllLabels() instead of getOriginalLabels() ?.

**Comment by Mulkave** [comment]
Yup sounds cool!

**Comment by tomb10516** [comment]
Hey guys,

I am trying to use this feature, but after I run addLabels on the model, they don't show up inside the model or when getDefaultNodeLabel is called.

I'm not sure if this is a bug.  If it is I have what I think is a patch, but I want to make sure I understand the intended functionality.  Patch at end:

Sample code:

$node = new ModelType();
$node->save;
$node->addLabels(["foo, "bar"]);
$node->save; // not sure if this save is required.  didn't check
dd($node).

The output of the dump shows only the original label in the label array.

Is this a bug?

If so I have what I think is a fix.  In updateLabels I added an array merge and everything appears to be working ok.

The only diff is the add of the line with the array_merge

        if($this->exists)
        {
            $saved = $this->setKeysForSaveQuery($query)->updateLabels($labels, $operation);
            $this->label = array_unique(array_merge($this->label, $labels));
            $this->fireModelEvent('updated', false);
        } else

**Comment by tomb10516** [comment]
Oh,

One more thing.  I think there is a mistake in the regular expression used to check whether the added label is valid.  It omits '_' which should be legal.

**Comment by tomb10516** [comment]
There is one or more bugs in my solution, but before I make a full patch I want to know whether I am going in the right direction.  What do you think?

**Comment by sameer-shelavale** [comment]
@tomb10516 that getDefaultNodeLabel is not supposed to return labels added with addLabels() method. also you dont need a save() after addLabels().
To retrieve all the labels i was going to add a function getAllLabels(), but I have got stuck in some daily project work and havn't got enought time to create that function and write Unit tests for it.

However, you may use this function I have used almost similar function while unit testing(in tests/functional/AddDropLabelsTest.php).
```
function getLabelsUsingEveryman($nodeId)
    {
        //get the labels using Everyman lib
        $connection = $this->getConnectionWithConfig('neo4j');
        $client = $connection->getClient();

        //check labels on w1
        $node = $client->getNode($nodeId);
        if( $node ) {
            $labels = $node->getLabels(); //get labels as array on the Everyman nodes
            $strLabels = array();
            foreach($labels as $lbl)
            {
                    $strLabels[] = $lbl->getName();
            }
            return $strLabels;
        }else{
            return [];
        }
    }
```

**Comment by tomb10516** [comment]
@sameer-shelavale 

Thanks!  I'm glad I asked before I put in a whole ton of work.

Do you think it would be useful for me to do a version of getAllLabels it with the current lib?  I think I'm going to do that on my fork of the repo since I'll need it for my own use.  What I don't know is which release candidate we would eventually merge it into.

Two questions:  

1: We should be supporting '_' in labels, right?
2: That the multiple labels aren't retrieved when the model is loaded is a bug, not intended functionality?
I ask because I don't want to start making existing functions do something they aren't supposed to like I was doing with getDefaultNodeLabel(). 

Thanks!

**Comment by sameer-shelavale** [comment]
@tomb10516 Abed is right person to answer those questions as he maintains this repo.
I replied because I had worked on that piece of code.
