### ISSUE TITLE
Inserting Strings and Timestamps in Database

### ISSUE THREAD

**Issue by sanjade** [Vinelab/NeoEloquent#290]
How do I actually insert string and timestamps in the database via this driver?

I tried `$label->string('first_name')` but it says `Undefined method: string()`! How can I make this work?

**Comment by oberoivarun** [comment]
What are you trying to do? Is this a migration?

**Comment by oberoivarun** [comment]
Migrations are used to create schema constraints and indexes. Not to actually input the data. Use eloquent methods for that. If you don't know what i am talking about, you are not ready to use this library. Study the docs and come back.

https://laravel.com/docs/5.6
