### ISSUE TITLE
  Call to undefined method Vinelab\NeoEloquent\Schema\Builder::defaultStringLength()

### ISSUE THREAD

**Issue by ardiantutomo** [Vinelab/NeoEloquent#297]
I'm using 
`php artisan neo4j:make create_user_graph_label --create=UserGraph`

it produce
`In Facade.php line 221:
                                                                               
  Call to undefined method Vinelab\NeoEloquent\Schema\Builder::defaultStringLength()`

What can i do for fixing this issue?

**Comment by holix** [comment]
Hey,

what version of NeoEloquent are you using?

Running `php artisan neo4j:make:migration create_user_graph_label --create=UserGraph` on 1.4.7 works fine.

**Comment by ardiantutomo** [comment]
I'm using v1.4.7
