### ISSUE TITLE
The problem of establishing a relationship

### ISSUE THREAD

**Issue by mrbardia72** [Vinelab/NeoEloquent#302]
https://github.com/Vinelab/NeoEloquent#one-to-one
---
How can I implement this section in Laravel's Controller?
This section is not well described
------
Please answer someone, this is my problem

**Comment by alex-jf** [comment]
Relations are described in model.

Please have a look at laravel documentation for model description. This should help:
[https://laravel.com/docs/5.6/eloquent-relationships#one-to-one](https://laravel.com/docs/5.6/eloquent-relationships#one-to-one)
