### ISSUE TITLE
Call to a member function lastInsertId() on null

### ISSUE THREAD

**Issue by asifnadaf** [Vinelab/NeoEloquent#304]
Hi,

I using Laravel 5.6 and NeoEloquent 1.4.7. I am getting following error while creating a record for new record on neo4j. However, the node gets created on Neo4j. 

/var/www/html/plusconnect.tk/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php
 
    /**
     * Process an  "insert get ID" query.
     *
     * @param  \Illuminate\Database\Query\Builder $query
     * @param  string $sql
     * @param  array $values
     * @param  string $sequence
     * @return int
     */
    public function processInsertGetId(Builder $query, $sql, $values, $sequence = null)
    {
        $query->getConnection()->insert($sql, $values);
 
        if ($sequence != null) {
            $id = $query->getConnection()->getPdo()->lastInsertId($sequence);
        } else {
            $id = null;
        }
 
        return is_numeric($id) ? (int)$id : $id;
    }
 
Arguments
"Call to a member function lastInsertId() on null"

The error goes away if the line below is commented from vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php
$id = $query->getConnection()->getPdo()->lastInsertId($sequence);

I am using the above solution as a workaround. What could be the issue?

May be it is expecting the primary key of the last record created and NeoEloquent is not receiving it.

Thanks

**Comment by smrsln** [comment]
Hi,
Probably you are using Eloquent class of Laravel for querying database.
If you have problem with your model about showing the Neoeloquent class try this:

`class User extends \NeoEloquent{}`

I hope it will solve your problem.

**Comment by asifnadaf** [comment]
Thanks I will try this solution and revert.
