### ISSUE TITLE
Missing Laravel 5.7 Support

### ISSUE THREAD

**Issue by DeltaBravo** [Vinelab/NeoEloquent#310]

**Comment by alex-jf** [comment]
Simple version bump should help.
PR in progress #314

**Comment by ivanlukic** [comment]
Any news about this PR? Thanks.

**Comment by jmurphy45** [comment]
Will there be any 5.7 support soon? @vinelabot

**Comment by ivanlukic** [comment]
What's the status with support for 5.7 and 5.8 ?

**Comment by jmurphy45** [comment]
@ivanlukic I am guessing that this repo is not being actively maintained right now.
