### ISSUE TITLE
 Declaration of Vinelab\NeoEloquent\Connection::select($query, $bindings = Array) must be compatible with Illuminate\Database\Connection::     select($query, $bindings = Array, $useReadPdo = true) 

### ISSUE THREAD

**Issue by sproutrahul** [Vinelab/NeoEloquent#312]
[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                    
  Declaration of Vinelab\NeoEloquent\Connection::select($query, $bindings = Array) must be compatible with Illuminate\Database\Connection::  
  select($query, $bindings = Array, $useReadPdo = true)

**Comment by uhkhil** [comment]
This issue occurs in Php 7.2, downgrading to 7.1 makes it work.
