### ISSUE TITLE
Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials()

### ISSUE THREAD

**Issue by lucasjovencio** [Vinelab/NeoEloquent#319]
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR) Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\User given, called in /projects/neo4jlaravel/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php on line 378

Laravel: 5.6
NeoEloquent: 1.4.7 I also tried with 1.4.6

Any solution?

[ERROR]
![capturar](https://user-images.githubusercontent.com/16108908/51429549-9bb8e000-1bf6-11e9-96c5-58abae1457c4.PNG)

[MODEL]
![image](https://user-images.githubusercontent.com/16108908/51429565-e9354d00-1bf6-11e9-9df2-7b1867a5a4d0.png)

[LOGIN]
![image](https://user-images.githubusercontent.com/16108908/51429576-1550ce00-1bf7-11e9-93bf-4fdc3b37c51e.png)

**Comment by lucasjovencio** [comment]
I succeeded in following the steps of  #144  

[MODEL]

![image](https://user-images.githubusercontent.com/16108908/51430472-053eeb80-1c03-11e9-8a2b-f4db81753486.png)

[RESULT]
![image](https://user-images.githubusercontent.com/16108908/51430483-20116000-1c03-11e9-95cf-94588987136e.png)

**Comment by just-pie** [comment]
Full code of User class?
