### ISSUE TITLE
Support for Laravel 5.8?

### ISSUE THREAD

**Issue by zhengdongquan** [Vinelab/NeoEloquent#325]

**Comment by KimPrince** [comment]
Is this on the schedule?  Or is the package no longer maintained?  I am about to start some Laravel / Neo4j projects and I am looking for an OGM.

**Comment by berteltorp** [comment]
At Ulobby we maintain a fork ulobby/neoeloquent, that has just been updated to work with 5.8 and we expect to support 6, well before 5.8 is EOL (February 26th, 2020).

We're also working on branch where we replace the underlying neo4j client with the official Neo4j node driver using a Rialto bridge.

We are committed to maintaining our fork, as we use it production 😅
