### ISSUE TITLE
Migrate to official Graphaware php client

### ISSUE THREAD

**Issue by KinaneD** [Vinelab/NeoEloquent#333]
**WIP*

## Neo4j Client Migration

NeoEloquent **1.5-dev**

#### createWith
1. Model::createWith()
2. Eloquent/Builder::createWith()
3. Query/Builder::createWith() -> `$this->connection->statement($cypher, [], true);`
4. ConnectionAdapter::statement()
5. NeoEloquent/Connection::statement()
	```
	$this->getClient()
                ->sendCypherQuery($query['statement'], $query['parameters']) // Get the raw http response, returns `Neoxygen\NeoClient\Formatter\Response`
                ->getResult(); // limit the response to results, discarding raw, body and rows, returns Neoxygen\NeoClient\Formatter\Result

	```
6. Eloquent/Builder::resultsToModelsWithRelations($connection, Neoxygen\NeoClient\Formatter\Result $results)
   6.1. $this->GetQuery->getGrammar()
   6.2. $results->getAllByIdentifier() // Reads identifiers retrieved from sendCypherQuery()->getResult()
    6.3. $this->shouldMutate($identifier)
    6.4. Eloquent/Builder::getMutationModel() // Return model class
    6.5. Eloquent/Builder::newModelFromNode() // Map node array to model
    6.6. Model::newFromBuilder()

#### Migration Guide
- Change `Connection::createSingleConnectionClient()`to use `GraphAware\Neo4j\Client\ClientBuilder` instead of `Neoxygen\NeoClient\ClientBuilder`
- Change `Connection::statement()` from using `$this->getClient->sendCypherQuery(…)` to `$this->getClient()->run(…)`
- Change `Neoxygen\NeoClient\Formatter\Result` to `GraphAware\Neo4j\Client\Formatter\Result`
- Change `Neoxygen\NeoClient\Formatter\Node` to `GraphAware\Neo4j\Client\Formatter\Type\Node`
- Create our own formatter to map `GraphAware\Neo4j\Client\Formatter\Result`
- Currently `Neoxygen\NeoClient\Formatter\ResponseFormatter::format()` populates `Neoxygen\NeoClient\Formatter\Result`
    - Refactor `Eloquent\Builder::resultsToModelsWithRelations()` and `Eloquent\Builder::resultsToModels()` to expect `GraphAware\Neo4j\Client\Formatter\Result`
    - Map properly graphaware’s result:
        - Instead of `identifiers` use `keys` i.e. placeholders
        - Instead of node use ($values[$index])->properties
        - How to deal with relationships? use `GraphAware\Neo4j\Client\Formatter\Type\Relationship`
- Transaction: `Client::__call()` -> `NeoClientCoreExtension::createTransaction()`. Instead of using the DB Facade, use `$client->transaction()->push(CYPHER);` or adapt it to the new syntax.
- Change `Eloquent\Builder::getNodeAttributres(Node $nodes)` and `Eloquent\Builder::newModelFromNode()` to use `$node->values();` instead of  `$node->getProperties();`.
- Remove `Eloquent\Builder::getProperties()` => `Undefined Class Row` Everyman.
- `Eloquent\Builder::mutateMorphToOrigin` uses deprecated `$result->getRelationships()` use new `getRelationshipRecords()` ? *AND* replace `$relationship->getProperty($mutationModelProperty)` WITH $relationship->get($mutationModelsProperty)}.
- `Query\Builder` uses invalid `$results->getAllByIdentifier()`, e.g. `Query\Builder::aggregate()`
- `Eloquent\Builder::eagerLoadRelations()` fail to load all relations
- `Edges\Finder::directionFromRelation` to not use `$relation->getStartNode()` anymore.

> Samples of the responses can be found in the attached html webpages. [Neo4j clients responses.zip](https://github.com/Vinelab/NeoEloquent/files/3570224/Neo4j.clients.responses.zip)

**Comment by heydavid713** [comment]
@KinaneD  how far along is this? Do you guys need any help with it?

**Comment by KinaneD** [comment]
Hey @heydavid713, we've got somewhere, providing support to causal clusters, but still considerable work and clean-up is required. You can take a look here https://github.com/Vinelab/NeoEloquent/tree/floobits/graphaware.

**Comment by SimonThordal** [comment]
Hey @KinaneD, I've been working on getting NeoEloquent to work with clustering by creating a bridge to the official Neo4j JavaScript driver using Rialto. I am thinking that the advantage is relying on an officially supported Neo driver. Could that work as an alternative solution for you?

**Comment by berteltorp** [comment]
A little update for posterity..

As @SimonThordal mentioned above we first thought it would be best to bridge the JS driver, but have since decided to go another route and port the python driver to php instead.

Porting the python driver to php is not a trivial task, and we haven't really gotten started yet.. but we still intend to it! 😅

**Comment by Mulkave** [comment]
@berteltorp @SimonThordal let us know how we can help! 😄
