### ISSUE TITLE
NeoEloquent in Laravel 8

### ISSUE THREAD

**Issue by cedvict** [Vinelab/NeoEloquent#342]
Hi Guy

I want to use this package to manage Neo4j database. I have an issue with this. It's not possible to install this in Laravel 8.

Please Someone can help ?
![image](https://user-images.githubusercontent.com/8941921/106511977-48f6ac00-64d1-11eb-89bd-3461cf08f848.png)

**Comment by berteltorp** [comment]
Hi @cedvict we have a fork with laravel 8 support over at [github.com/ulobby/NeoEloquent](https://github.com/ulobby/NeoEloquent)

**Comment by cedvict** [comment]
Thanks you very much

But I have some issue again with the ulobby/NeoEloquent

![image](https://user-images.githubusercontent.com/8941921/106650755-920f3480-6593-11eb-8e57-485a70d81078.png)

Dont understand what happens.

**Comment by wkasem** [comment]
i had a similar issue , 
make sure when you re creating new neo4j database to select version < 4 
in new versions of neo4j they changed the way to get server info 
still an issue though with NeoEloquent package , it should be compatible with  new versions of neo4j

**Comment by cedvict** [comment]
Thanks for your reply

I change the neo4j server to 3.5.26

When I try to execute neo4j:migrate:reset, I get this
![image](https://user-images.githubusercontent.com/8941921/107045051-5d82bf00-67c5-11eb-9554-905a50b32a1e.png)

I use ulobby/neoeloquent v8.0 in laravel v8

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by Mulkave** [comment]
Laravel 8 is now supported and has the official [Neo4j-php](https://github.com/neo4j-php/neo4j-php-client/) driver integrated. Thank you for your patience, long wait is over; we've been working hard along with @transistive (author of Neo4j-php) to get this done right.
