### ISSUE TITLE
Getting Undefined offset for find() in laravel 5.6

### ISSUE THREAD

**Issue by pradeep-upadhyaya** [Vinelab/NeoEloquent#344]
Hi, I  am using laravel: 5.6 and vinelab/neoeloquent: 1.4.6.

I have built a simple laravel login app and saving sessions in the database. If I enter to this URL`localhost:8081/login` I am getting the below error.

```
Undefined offset: 0
```
this error is triggering by the below line
```
$session = (object) $this->getQuery()->find($sessionId);
```

If I remove `find()` in the above line it will redirect to the login page successfully(but not able to log in). 

Can anyone help me out to solve this? Let me know if anyone needs more details. Thank you.

**Comment by Mulkave** [comment]
@pradeep-upadhyaya please update your NE installation to v1.5 (the latest) and try again. Thank you for your patience, we've been a bit stale but now back in activity with the latest version of the official [Neo4j-php driver](https://github.com/neo4j-php/neo4j-php-client/). Good luck!

If you happen to face the same problem please let us know by reopening this issue.
