### ISSUE TITLE
NeoEloquent laravel 8

### ISSUE THREAD

**Issue by plolp20** [Vinelab/NeoEloquent#345]
Hi, I am using laravel 8 and neo4j desktop 1.4.5 i want create node from a json file with laravel 
this my code php :
public function addneouds()
{
  $json = json_decode(file_get_contents('C:\Users\USER\Desktop\neo4j\public\etudiants.json'));
 
for($i=0;$i<count($json);$i++)
DB::connection('neo4j')->select('create(n:etudiants) return n'); 
foreach($json as $cle => $elem)
{
  foreach ($elem as $c => $v){
      echo $c. ' : ' .$v. ',';
DB::connection('neo4j')->select('match (n:etudiants)  set n={'.$c.':'.$v.',}');
}
echo "$cle: $elem <br />";
}
return "inserted";
}
but i have this error ,please can you help me:
Vinelab\NeoEloquent\QueryException
SyntaxException: Invalid input '}': expected whitespace or a property key name (line 1, column 34 (offset: 33)) "match (n:etudiants) set n={id:9,}" ^

**Comment by ayounglad** [comment]
Would like to add my support for getting this project working for the latest version of Laravel. Is anyone working on updating this repo to work with Laravel 8? Should it be refactored?

**Comment by Mulkave** [comment]
And now it's [officially supported](https://github.com/Vinelab/NeoEloquent/issues/342#issuecomment-977631971). Thanks for your interest in contributing @mr-adam-young and sorry for the long wait.
