### ISSUE TITLE
Guarded fields

### ISSUE THREAD

**Issue by demirhancosku** [Vinelab/NeoEloquent#35]
Hello!
Protecting some fields is really crucial in most of the applications, especially for apps that implements user authentication.
In eloquent we have this;
 protected $guarded = ['id', 'password'];

Is it going to be in roadmap as feature?

**Comment by Mulkave** [comment]
Did you face any issues using Guarded fields ?

**Comment by demirhancosku** [comment]
No we didn’t. Thank you for your interest.

**Comment by Mulkave** [comment]
Good to hear!
