### ISSUE TITLE
Laravel 8 release appears to be completely broken

### ISSUE THREAD

**Issue by kirkbushell** [Vinelab/NeoEloquent#350]
I tried working with your library today, and when trying to implement it came across problem after problem, as the API being used for the grammar classes do not match the interfaces and grammar classes from Laravel.

I fixed at least 25 errors/issues before realising this I think needs to be completely redone, @transistive 

Am running Laravel 8.74.

**Comment by transistive** [comment]
Thank you @kirkbushell,

I will start working on a solution this weekend :+1: 

Thank you for your patience

**Comment by kirkbushell** [comment]
Just an FYI, the experience has given me no confidence in the project, so I started working on my own solution just using repositories and effectively a cypher builder.

**Comment by transistive** [comment]
Good luck! If you want we can work together via this project, we can use all the help available!

I am in the process of cleaning up the entire library but it takes a while. There is also this amazing project (WIP) https://github.com/WikibaseSolutions/php-cypher-dsl which we are discussing to implement here or not as a dependency

**Comment by mrspence** [comment]
> Good luck! If you want we can work together via this project, we can use all the help available!
> 
> I am in the process of cleaning up the entire library but it takes a while. There is also this amazing project (WIP) https://github.com/WikibaseSolutions/php-cypher-dsl which we are discussing to implement here or not as a dependency

Are you updating it on this branch? :-) 

https://github.com/Vinelab/NeoEloquent/tree/v1.8

**Comment by Mulkave** [comment]
@kirkbushell @mrspence thank you for your patience. Indeed that first release was premature and should've been marked as such (pre-release and with an `alpha` sign). We've just released a stable version that works `v1.8.1` please go ahead and update your `composer.json` to pull that version by specifying `^1.8.1`.

Sorry for the inconvenience.

**Comment by kirkbushell** [comment]
> There is also this amazing project (WIP) https://github.com/WikibaseSolutions/php-cypher-dsl which we are discussing to implement here or not as a dependency

Honestly, I gave that a go but the code is so verbose and difficult to read that I gave it a pass and made a much simpler DSL with the requirements I needed.

I'll give NeoEloquent another go, but I'm already well passed needing it now.

**Comment by kirkbushell** [comment]
Sorry guys, but this is still massively broken.

On trying to install:

> Class Vinelab\NeoEloquent\Migrations\DatabaseMigrationRepository contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods

It's a solid pass on me with this project, it seems to be missing the basic requirements of running an Open source project I'm afraid.
