### ISSUE TITLE
2 abstract method that need to be implemented before using the package

### ISSUE THREAD

**Issue by holiday526** [Vinelab/NeoEloquent#351]
Hi there,

I am new to neo4j and I wanna use your package for my personal projects in neo4j. However, when I install your package, it prompts two errors and ask me to implement 2 methods before serving the Laravel application.
I try to Google it, but there is no solution.

I really want to use your package for development. Please help. Thanks.

Laravel version: 8.65
PHP version: 7.4.23

![image](https://user-images.githubusercontent.com/48387601/145708436-07296caf-b36e-432b-b4ba-50c551d17821.png)

**Comment by transistive** [comment]
Hello @holiday526,

Thank you for bringing awareness to the issue. We are working hard on fixing it. It should be merged and fixed by Sunday.

Kind regards,

Ghlen
