### ISSUE TITLE
Undefined property: Vinelab\NeoEloquent\Query\Builder::$joins

### ISSUE THREAD

**Issue by rezaamini-ir** [Vinelab/NeoEloquent#358]
When we are using SoftDelete with $dates property in our model it will retrieve an error in get actions.

![Screenshot from 2022-03-13 19-00-31](https://user-images.githubusercontent.com/29504334/158067224-eeb6474e-3244-46ff-a2b3-5b284790171d.png)

**Comment by Mulkave** [comment]
Could you please provide some more context on the model and what you were doing to get this? was it just deleting the record with soft deletes enabled?
