### ISSUE TITLE
Where Patterns

### ISSUE THREAD

**Issue by BrummbQ** [Vinelab/NeoEloquent#41]
Currently I'm unable to execute patterns in where clauses (http://neo4j.com/docs/2.1.6/query-where.html#query-where-patterns) with the query builder.

$query = Model::query();
$query->where('uuid', 'IN', [1, 2, 3]);

That query doesn't evaluate to the correct cypher string, hence the result set will be wrong. Glad if you could help me.

**Comment by Mulkave** [comment]
This is confirmed to be a bug, unfortunately this and other advanced patterns like `[x]` and `[x..y]` haven't been thoroughly tested. Meanwhile you may use

```php
$query->whereIn('uuid', [1, 2, 3]);
```

Sorry for any inconvenience this might have brought.
