### ISSUE TITLE
Database neo4j not configured error:

### ISSUE THREAD

**Issue by akulkarni9** [Vinelab/NeoEloquent#42]
Hi, 
I used installation procedure as you mentioned, wrote a model for form data storing. Here is my model:     

    <?php

    namespace Vinelab\Cms;

    class Duck extends NeoEloquent {

	protected $fillable = array('name', 'email', 'password');
	
	public function index($name, $email, $password, $password_confirm) {
			
		$formData = Neo4j::makeNode();
		$formData->setProperty('name',$name)
		->setProperty('email',$email)
		->setProperty('password',$password)
		->setProprty('password_confirm',$password_confirm)
		->save();
			
	}

    }
I gave connections as:
    'connections' => [
 		'neo4j' => [
			'driver' => 'neo4j',
			'host'   => 'localhost',
			'port'   => '7474',
			'username' => null,
			'password' => null
		]
	],
When I submit the data, it returns an error like this: 
![selection_082](https://cloud.githubusercontent.com/assets/7793763/5855374/95e9ec4e-a25d-11e4-9177-3c810d6f920a.png)
How can I fix it?

**Comment by Mulkave** [comment]
You need to specify `default => neo4j` here's an example:

```php
return array(

    'default' => 'neo4j',

    'fetch' => PDO::FETCH_CLASS,

    'connections' => array(

        'neo4j' => array(
            'driver' => 'neo4j',
            'host' => 'localhost',
            'port' => 7474,
        ),
    ),
)
```

**Comment by akulkarni9** [comment]
Yeah, I figured it out. Thank you

Ajay Kulkarni
Engineering and product
Cheerz Labs
+91-9482780814
