### ISSUE TITLE
Support Laravel 5 ?

### ISSUE THREAD

**Issue by eIiam** [Vinelab/NeoEloquent#46]
Hey,

It is planned to support ?

just a question... i didn't try anything 

thanks

**Comment by Mulkave** [comment]
sure thing!

**Comment by jonaswouters** [comment]
Any roadmap to support it? :)

**Comment by Mulkave** [comment]
Yup, will be delivered by end of day :)

**Comment by Mulkave** [comment]
This has taken longer than expected, sorry for the delay. Work is in progress..

**Comment by eIiam** [comment]
Great ! Thanks a lot !

**Comment by Mulkave** [comment]
@eIiam Cheers :beers:
