### ISSUE TITLE
Case Insensitive where conditions

### ISSUE THREAD

**Issue by ShindeSatish** [Vinelab/NeoEloquent#48]
Suppose I need to get user information according to username

How can I execute following query from NeoEloqunt 
Example: MATCH (u:user) where u.username = '(?i)satish';

Need to have where condition case Insensitive. 

Or is there any functionality like DB::raw 

Please help me on this.

**Comment by Mulkave** [comment]
Have you tried `User::where('username', '(?i)satish');` ?

**Comment by ShindeSatish** [comment]
Thanks for your quick response,
I tried this but it doesn't work for 
User::where('username','(?i)satish')->first();

Is there any thing i missing here

**Comment by Mulkave** [comment]
are you getting any error messages or exceptions that you can share ?

**Comment by ShindeSatish** [comment]
No errors, I just got blank response

**Comment by Mulkave** [comment]
hmm I'll have to look into this on my side, what I suggest is:
- make sure there's a record that would match the `useraname` you're trying to match
- use `whereRaw` as a workaround until I get the time to try it out, i.e. `$model->whereRaw("slug REGEXP '^{$slug}(-[0-9]*)?$'")->count()` replace the raw query with what you would like to match.

Sorry for any inconvenience this have caused.

**Comment by ShindeSatish** [comment]
I double checked that record is present in the database.

For now I will try whereRaw()

Thanks for your help

**Comment by pchaow** [comment]
you can try this 
$query->orWhere($key, '=~', "(?i).*$value.*");

**Comment by Mulkave** [comment]
Actually true what @pchaow mentioned, that slipped my mind.. you have to use the `=~` operator in order to get what you're looking for. I guess this closes it, please inform if you still face issues.
