### ISSUE TITLE
Can I get executable query 

### ISSUE THREAD

**Issue by ShindeSatish** [Vinelab/NeoEloquent#50]
I want to check The Cypher performed query by this statement.

For example- 
$user = User::find(1);
$post = new Post(['title' => 'The Title', 'body' => 'Hot Body']);
$user->posts()->save($post);

For this statement following Cypher query will get generated 
MATCH (user:`User`)
WHERE id(user) = 1
CREATE (user)-[rel_user_post:POSTED]->(post:`Post` {title: 'The Title', body: 'Hot Body', created_at: '15-05-2014', updated_at: '15-05-2014'})
RETURN rel_user_post;

How can I get Cypher query performed by the statement.

Thanks

**Comment by Mulkave** [comment]
In order to get the full query log you may use the following:

```php
(new User)->getConnection()->getQueryLog();
```

Which will return an array containing all the queries that were run till the moment you call this method.

Or if you have an instance already you may call `$user->getQueryLog()`

**Comment by pchaow** [comment]
Thanks , I've tried to find this method long time ago.
