### ISSUE TITLE
Laravel 5 support 

### ISSUE THREAD

**Issue by ShindeSatish** [Vinelab/NeoEloquent#53]
Hi @Mulkave,

Thanks for great library, It is so useful

I just wanted to know, when do you planning to provide support for laravel 5.

**Comment by eIiam** [comment]
It's done !

**Comment by ShindeSatish** [comment]
Yes, I seen that now  :)  Got at the right time :)

**Comment by Mulkave** [comment]
@ShindeSatish Glad to know that this package is of benefit for you. As @eliam mentioned it is now supported! You may use:

```json
{
   "vinelab/neoeloquent": "1.2.*"
}
```

to require it in L5. Enjoy!
