### ISSUE TITLE
Give support to relationship

### ISSUE THREAD

**Issue by DipakDendage** [Vinelab/NeoEloquent#54]
HI,

Please give support to relationship entity so we can fetch relationship records.

If already have any suggestion then please let me know ?

**Comment by Mulkave** [comment]
Can you please provide an example of what you are trying to achieve ?

**Comment by DipakDendage** [comment]
Sorry Mulkave,

Example : 
Cypher query is : 

WITH ( u : user ) - [r:OWNER_OF]->( v: vehicle )
WHERE id(u) = 123
RETURN v,r;
 
How can I achieve this query result with NeoEloquent?

**Comment by Mulkave** [comment]
This can be done currently using [Eloquent's Eager Loading](http://laravel.com/docs/5.0/eloquent#eager-loading) and applying the `with($relations)` method to the query.

**Comment by Mulkave** [comment]
It could actually be an improvement to load relations this way rather than extra queries as in Eloquent.

**Comment by taciomedeiros** [comment]
When i use with the results are duplicated, and the distinct() doesn't work
