### ISSUE TITLE
Need to store created_at and updated_at in the timestamp

### ISSUE THREAD

**Issue by ShindeSatish** [Vinelab/NeoEloquent#55]
Currently, When I create a node "created_at" and "updated_at" properties will get saved with datetime value like "2015-02-26 13:48:23".

I want to store created_at and updated_at as timestamp like "1424958999193". How can I do this?

**Comment by Mulkave** [comment]
You have to override the method `getDateFormat()` in your model:

```php
protected function getDateFormat()
    {
        return 'U';
    }
```

**Comment by Mulkave** [comment]
@ShindeSatish did this solve it for you ?

**Comment by ShindeSatish** [comment]
@Mulkave  Yes, Thanks :)
