### ISSUE TITLE
PDO instance returns as null

### ISSUE THREAD

**Issue by marlongichie** [Vinelab/NeoEloquent#61]
Using eloquent models it's possible to retrieve the underlying PDO instance by using:
```
$pdo = DB::connection()->getPdo();
```
However, this seems to return `null` using the `neo4j` connection

Can someone point me in the right direction to get this working?

Best,

**Comment by aymanfarhat** [comment]
Its expected to return null because there is no PDO instance that NeoEloquent is relying on. Alternatively, you can get an instance of the neo4jphp client via `DB::connection('neo4j')->getClient();`. Hope that helps.

**Comment by marlongichie** [comment]
Thank you at @aymanfarhat .

I thought that might be the case. I was able to work around it by using the PDO instance supplied by the mysql driver.

Seems to work as expected just the same.

Best,
