### ISSUE TITLE
Possible to use forceDelete?

### ISSUE THREAD

**Issue by marlongichie** [Vinelab/NeoEloquent#62]
Standard Eloquent has the option to fully remove a model from the database using the forceDelete method:

Example: `$user->forceDelete();`

The forceDelete method also works on relationships:
`$user->posts()->forceDelete();`

I tried using it but it seems to throw an error:

```
Vinelab \ NeoEloquent \ QueryException

Unable to execute query [500]: Headers: Array ( [Access-Control-Allow-Origin] => * [Content-Type] => text/html; charset=ISO-8859-1 [Cache-Control] => must-revalidate,no-cache,no-store [Content-Length] => 0 [Server] => Jetty(9.0.5.v20130815) ) Body: Array ( ) 
```

**Comment by Mulkave** [comment]
Don't have this tested, will look into it. Thanks!
