### ISSUE TITLE
Incorrect response returned when query relationship

### ISSUE THREAD

**Issue by bobflay** [Vinelab/NeoEloquent#64]
in Many to Many relationship (user  question) example:
a user has many questions
a question belongs to many users
if i want to get a specific question of a specific user i always get the first question ex:

``` php
$user->questions()->where('id',2)->first();
```

it return the first question and not the second question, while doing the same query with mysql return the second question

using Eloquent

![using Eloquent](https://cloud.githubusercontent.com/assets/1891656/7099338/807a0a6c-dff0-11e4-9c53-89d812dc35ac.png)

using NeoEloquent

![using NeoEloquent](https://cloud.githubusercontent.com/assets/1891656/7099341/90b03e56-dff0-11e4-8a56-a675c312aaf5.png)

graph Db showing that 9526 is the id of the q2

![graph Db showing that 9526 is the id of the q2](https://cloud.githubusercontent.com/assets/1891656/7099345/a70f25cc-dff0-11e4-88ef-c1ebc5df8b82.png)

**Comment by Mulkave** [comment]
According to the [docs of Querying Relations](http://laravel.com/docs/5.0/eloquent#querying-relations) your query doesn't deal with querying the questions, what it's doing is asking for the *user with the ID 2* as for querying the questions:

```php
$user->whereHas('questions', function($q) {
    $q->where('id', 2);
})->first();
```

Unless I'm misunderstanding your issue, this should solve it.

**Comment by Mulkave** [comment]
Did u get a chance to try that out ?

**Comment by bobflay** [comment]
yes and it returns null using your query,

![screen shot 2015-04-19 at 2 33 34 pm](https://cloud.githubusercontent.com/assets/1891656/7219457/2f6ea2e2-e6a1-11e4-893c-5ed2045b4187.png)

knowing that i'm asking for question id ```3370``` and it returns to me question id ```3769```.

**Comment by Mulkave** [comment]
what is the ID of the `User` returned in that result?
