### ISSUE TITLE
Update Docs for soft deleting 

### ISSUE THREAD

**Issue by adibhanna** [Vinelab/NeoEloquent#65]
to use soft deleting we need to use `use Vinelab\NeoEloquent\Eloquent\SoftDeletes;` 
and not `use Vinelab\NeoEloquent\Eloquent\SoftDeletingTrait;`

**Comment by Mulkave** [comment]
Make sure you're looking at the correct branch, `1.2` is for Laravel 5 with `SoftDeletes` instead of `SoftDeletingTrait`
