### ISSUE TITLE
Consider implementing a case-insensitive "LIKE"-esque operator

### ISSUE THREAD

**Issue by lamoni** [Vinelab/NeoEloquent#73]
What are your thoughts on implementing a "shortcut" for doing a ->where() that auto-prepends '(?i)' for the =~ operator?  I believe this is the closest equivalent to SQL's "LIKE".  I find myself having to do this in multiple projects I'm working on (I know, I know, not a good reason), and despite the "LIKE" operator not existing in Neo4j, we could implement something close to it, relatively easily.

**Comment by Mulkave** [comment]
Sorry for the late reply.

Have used it much myself as well, and I see the benefit of that even if it's not the perfect reason to have it :smile: 

Is there anything like that in Eloquent ? If not how do you see it in an Eloquent-ish way?

Probably something like `Model::whereLike('something')` ?!

**Comment by lamoni** [comment]
Exactly my thoughts!  whereLike() seems like a great candidate.

**Comment by ctorresrodz** [comment]
Is there a ETA on thjis LIKE operator?
