### ISSUE TITLE
Can I create this cypher with NeoEloquent

### ISSUE THREAD

**Issue by pchaow** [Vinelab/NeoEloquent#74]
Hi, 
I want to know how to create statement that do the same thing like this cypher query.

MATCH (c:Category) WHERE NOT (()-[:HAS_CATEGORY]->(c)) RETURN c

Thanks

**Comment by Mulkave** [comment]
Sorry for the late reply.

I assume your models look something like this:

```php
class Category {

  protected $label = 'Category';

  public function things()
  {
    return $this->hasMany('Thing', 'HAS_CATEGORY');
  }

}
```

```php
class Thing {

  protected $label = 'Thing';

  public function categories()
  {
     return $this->hasMany('Category', 'HAS_CATEGORY');
  }

}
```

should be doable with `whereHasNot`, probably something like `Category::whereHasNot('things')`

**Comment by Mulkave** [comment]
@pchaow any updates on the above?

**Comment by pchaow** [comment]
@Mulkave, Sorry for late replied, It's work.
