### ISSUE TITLE
Fetching relations with attributes 

### ISSUE THREAD

**Issue by tomb10516** [Vinelab/NeoEloquent#75]
Hey folks!

This is a call for discussion of potential new features.

I've been interested for a while now in what it would take to add attribute operations to relations in NeoEloquent.

I saw a post about this on stackoverflow (link at bottom of this post), and I thought I'd bring it over here so we can continue the discussion.

So what are the difficulties that would have to be faced to add these features?  Is it a matter of implementation or are there also fundamental design aspects?

stackoverlfow link: https://stackoverflow.com/questions/27146398/how-to-get-records-by-checking-relationship-attributes-in-laravel-neoeloquent

**Comment by Mulkave** [comment]
@tomb10516 glad to hear about your interest in such feature, it has to do more with design rather than implementation.

How would you imagine querying "Eloquently" a relationship/edge by attributes could look like?

**Comment by tomb10516** [comment]
Excellent question :-)

Forgive me if I could answer this with a quick google search, but has anyone written up Eloquent grammar as a formal grammar?  I've written compilers before (for research projects, nothing anyone would actually want to use!) and am used to thinking of things in formal language theory.  If I see the current Eloquent grammar in those terms I might be able to more easily offer an extension to the current grammar.

If there isn't such a thing I'll try to write out just the immediately relevant parts of NeoEloquent as a grammar.

**Comment by Mulkave** [comment]
Eloquent follows the Builder Design Pattern mostly, so whenever you call a function like `where()` or `order()` etc. Eloquent is collecting this information about the query, then when a `get()` or `first()` or `paginate()` is called the query is compiled into Cypher using the `CypherGrammar` class then executed against the desired connection.

The question was actually more about how do you see it being used in NeoEloquent. *i.e. `User` has many `Posts`* and we want to fetch those posts where the relationship was created before the current time, the code would look something like this ?! (just guessing):

```php
User::posts(function($relation){
   $relation->where('created_at', '<', Carbon::now());
})->get();
```

**Comment by tomb10516** [comment]
Hey folks!

I have implemented searching on edges and I'd like some comments.  I am still cleaning up and testing, but I'd like comments on the basic approach.

I decided to create a whereRel() method instead of trying to overload where().  The reason is that by using whereRel you can combine filters on edges and nodes in the same statement.  The implementation is a little clunky, and many features of where() are not supported such as nesting.  It also has a limitation that only one relation may appear in a given statement.

You can look at the test testFilterRelationProperties() in https://github.com/tomb10516/NeoEloquent/blob/relationProperties2/tests/functional/QueryingRelationsTest.php to see a demo of the basic usage.

So if there are a bunch of User and they have a relationship with Organization such that 

class Organization extends Model {
   
    public function members()
    {
        return $this->hasMany('Vinelab\NeoEloquent\Tests\Functional\QueryingRelations\User', 'MEMBER_OF');
    }
}

If the MEMBER_OF edge has a property called $organization->members()->edge($user)->status
You can find users with their membership status set to 'active' with

$organization->members()->whereRel('status', '=', 'active')->get();

If you wanted to find active users who are named "bob":

$organization->members()->whereRel('status', '=', 'active')->where('name', '=', 'bob)->get();

What do you think?

**Comment by Mulkave** [comment]
@KinaneD thoughts?

**Comment by Mulkave** [comment]
On second thought about this (I know it might be too late to say this), why don't we overload the relationship function itself where we can do something as follows:

```
$organization->members(Closure to query by relationship properties)->get()
```

So to fetch the members that are active in an organization:

```php
$organization->members(function($query) {
    $query->where('status', '=', 'active');
})->get();
```

IMO this is a "familiar" behaviour due to the similarities with `whereHas` and other methods.

@tomb10516 @KinaneD ?

**Comment by tomb10516** [comment]
As you know, I am relatively new to PHP, having spent much more time in languages that allow function overloading by function signature.

Without overloading by signature, how would this work?

And would the user have to change all of their relation functions to look like

    public function members(\Closure $func = null)
    {
        return $this->hasMany('Vinelab\NeoEloquent\Tests\Functional\AttributeRelations\User', 
            'MEMBER_OF', null, null, $func);
    }

Sorry I'm being dense.

**Comment by Mulkave** [comment]
@tomb10516 you're right about the signature thing, haven't thought it out when I was suggesting I was more concerned about the end result instead. I'll give it another shot within the context of keeping it Eloquent-y :smile: to be honest `whereRel` doesn't ring that bell for me you know... maybe `whereEdge` might have to do more with NE since we already have `edge()` and `edges()`. Thoughts?

**Comment by tomb10516** [comment]
whereEdge is better.  Under the hood it attempts to follow the structure of where() as much as possible.

**Comment by decebal** [comment]
Any signs of this in production ?
