### ISSUE TITLE
Does the createWith method fire model events?

### ISSUE THREAD

**Issue by marlongichie** [Vinelab/NeoEloquent#78]
I am trying to use the `createWith` method to save a model with relationships, and then perform some other action when the model's `creating` event is fired.

However, it seems event firing does not happen when using `createWith`. I have tried to `dd('creatiing')` from the model's creating event to check, but nothing happens.

Note, that the event fires as expected when using the `create` method.

Anyone else experiencing this? Suggestions?

**Comment by Mulkave** [comment]
This was added on this commit https://github.com/Vinelab/NeoEloquent/commit/33d9f421261116815d0b686973edcc075c54c04c

But it's currently on the `1.2.5` branch which supports Laravel 5 only. Are you using it with L4 ?

**Comment by marlongichie** [comment]
Yes, I am using L4.2. 

Possible to get this functionality or no?

**Comment by Mulkave** [comment]
@marlongichie sorry for taking too long on this, been prioritising other aspects of the package. Just wondering if you're still on L4 to evaluate this feature ?

**Comment by marlongichie** [comment]
@Mulkave I've since moved over to L5 since this feature was a major requirement. Can't speak to whether this has been fixed or not.

**Comment by tomb10516** [comment]
@marlongichie 

The code in 1.2.6 has the following comment:
        // we need to fire model events on all the models that are involved with our operaiton,
        // including the ones from the relations, starting with this model.

If the code doesn't do what the comment says please let me know and I will try to fix.

**Comment by tomb10516** [comment]
Sorry, I should have given more context to the comment:

 public static function createWith(array $attributes, array $relations, array $options = [])
    {
        // we need to fire model events on all the models that are involved with our operaiton,
        // including the ones from the relations, starting with this model.

Later on in the function there is a foreach loop that instantiates each related model which should work as far as I can see, although I don't have time to write a functional test unless it seems to be buggy.
