### ISSUE TITLE
Sorting a ResultSet?

### ISSUE THREAD

**Issue by lamoni** [Vinelab/NeoEloquent#81]
Due to no support for ORDER BY'ing a UNION result in Neo4j, I have to resort to sorting the results in code.  Is this possible with NeoEloquent's ResultSet class somehow?

**Comment by Mulkave** [comment]
NeoEloquent's ResultSet is this class https://github.com/jadell/neo4jphp/blob/master/lib/Everyman/Neo4j/Query/ResultSet.php

It doesn't have much in terms of sorting, but it implements `Iterator` and `ArrayAccess` which makes it easy to just loop through it or have it as an array.

**Comment by lamoni** [comment]
Ahhh okay thanks!  Thought so, but wanted to double-check :).  Will close
