### ISSUE TITLE
Compatibility with the version of Eloquent used in Laravel master branch

### ISSUE THREAD

**Issue by tomb10516** [Vinelab/NeoEloquent#83]
The version of Eloquent that will be used for Laravel 5.1 is not compatible with NeoEloquent since the Eloquent people changed the number of arguments to a method in a way that breaks backwards compatibility.  At a quick look it seems like fixing this should be easy on our (NeoEloquent) side, but I don't have time to do it now.  We (my company) tried moving our projects to 5.1 over the weekend, but this morning I just rolled back to our pre-upgrade commits.

The problem we ran in to was in \Illuminate\Database\Eloquent\Builder::simplePaginate().  In Laravel 5.0 this has 2 arguments, in 5.1 it has 3 arguments.  From the Laravel docs:

http://laravel.com/api/5.0/Illuminate/Database/Eloquent/Builder.html  -- simplePaginate(int $perPage = null, array $columns = array('*'))

http://laravel.com/api/master/Illuminate/Database/Eloquent/Builder.html -- simplePaginate(int $perPage = null, array $columns = array('*'), string $pageName = 'page')

I may fix this depending on how urgent it is versus the other NeoEloquent things I am working on.  Is this issue urgent for any of you?

**Comment by Mulkave** [comment]
This should've been addressed with https://github.com/Vinelab/NeoEloquent/commit/86b7e34fa68951efc28dc20c434b6960c717ad34

Not sure what version you're using but make sure it's the latest of `1.2.5` and `composer.lock` should have dropped this commit ID: 7e32b3b8d68f9ac8bfb0e05b260d1e178c6c45af

**Comment by bradmsmith** [comment]
@Mulkave Looks like this update was pushed into the 1.2.5 branch but is missing from the 1.2.5 tag on the master branch. Is that intentionally? Should I require the 1.2.5 branch in composer instead of master if I need this?

**Comment by Mulkave** [comment]
@bradmsmith please note that the `master` branch lacks support for L5, `1.2.*` is the version that supports L5 so it depends on your Laravel version.
