### ISSUE TITLE
Multiple whereHas statements in a single query always returns null

### ISSUE THREAD

**Issue by marlongichie** [Vinelab/NeoEloquent#86]
When I run a query that includes multiple `whereHas` statements as shown in the function below, the result is always `null`.

If I comment out either one of the `whereHas` statements and run the query, I get the expected result.

Am I not using this correctly, or is this not possible with NeoEloquent?

```
public function getVehicle($make_slug, $model_slug)
{
        $vehicle = $this->vehicles()
                ->whereHas('make', function($query) use ($make_slug)
                {
                    $query->where('slug', $make_slug);
                })
                ->whereHas('model', function($query) use($model_slug)
                {
                    $query->where('slug', $model_slug);
                })
                ->first();

        return $vehicle;
}      
```

**Comment by Mulkave** [comment]
Can you please paste in the query that is executing with both and with any of them removed? you can get them by running `Model::getQueryLog()`

**Comment by tomb10516** [comment]
@marlongichie 

I think this is related to a bug I have fixed, but my fix isn't yet tested enough for me to generate a pull request.  Would you try https://github.com/tomb10516/NeoEloquent/tree/1.2.6 and see if this fixes your problem?
