### ISSUE TITLE
 [Symfony\Component\Debug\Exception\FatalErrorException]   Class 'Vinelab\NeoEloquent' not found

### ISSUE THREAD

**Issue by IgnitedCoder** [Vinelab/NeoEloquent#87]
No matter what I try.. L5.1 seems to be the culprit, works just fine in 5.0... Any chance the service provider needs to change for L 5.1? Assistance getting this resolved would be most appreciative.

Thanks,
Brendan

**Comment by IgnitedCoder** [comment]
Please update the docs, this is what worked for me - use Vinelab\NeoEloquent\Eloquent\Model as NeoEloquent;

Enjoy.

**Comment by Mulkave** [comment]
@IgnitedCoder thanks for the tip. Seems like L5.1 have a few changes that need an update, hopefully in a couple of days.
