### ISSUE TITLE
Support for multiple database connections (read/write)

### ISSUE THREAD

**Issue by lamoni** [Vinelab/NeoEloquent#90]
Referring to: http://laravel.com/docs/5.0/database#read-write-connections

I don't think the support for this is here and I'd like to add it.  Can I get confirmation that this feature isn't already in process, and can I also get confirmation that it's not already here (I was trying the read/write array items in the config but didn't seem to affect it at all).

Thanks

**Comment by lamoni** [comment]
Working version here, but won't send a PR due to I'm working on figuring out if I can leverage the already existing "readPdo" var to do this, instead of creating new vars ($neoRead, for example):

https://github.com/lamoni/NeoEloquent/blob/1.2.5/src/Vinelab/NeoEloquent/Connection.php

Configuration example:

```
		'neo4j' => [
			'driver' => 'neo4j',
			'read' => [
                'host' => 'localhost'
            ],
            'write' => [
                'host' => 'localhost'
            ],
			'port'   => 7474,
			'username'  => env('DB_USERNAME', 'forge'),
			'password'  => env('DB_PASSWORD', '')
		]
```

**Comment by Mulkave** [comment]
Due to the use of https://github.com/neoxygen/neo4j-neoclient in v1.5 this should be easily done since it supports HA out of the box, might need support here as well though. This version is still under development and tests haven't all been covered yet, but it's the focus at the moment.

**Comment by lamoni** [comment]
Hey @Mulkave 

Sorry for the silence on this.  I wanted to check in on if this was planned for support?  If not, I can PR on the latest

**Comment by Mulkave** [comment]
@lamoni a PR would be much appreciated :smile:

**Comment by AzeemMichael** [comment]
is this still an open issue? Or has this been merged in the production?

**Comment by AzeemMichael** [comment]
is there any update on when the version 1.5 be released?
