### ISSUE TITLE
Parameter Binding?

### ISSUE THREAD

**Issue by lamoni** [Vinelab/NeoEloquent#93]
Is there support for parameter binding to avoid Cypher Injection?

**Comment by Mulkave** [comment]
If you mean behind the scenes then definitely. Although in certain cases it's not used but the parameters are always cleaned before use. Called `propertize` inside.

**Comment by lamoni** [comment]
Ahh okay thanks, I'm assuming the santizing doesn't handle things like wildcards, etc...?  I have an instance where I'm doing something like:

Model::where("name", \Input::get('someparameter'))

And if I pass in .* it will evaluate and find something due to it being a wildcard.

**Comment by Mulkave** [comment]
Yes, since a wildcard is available for use with regex pattern matching such as `n.name =~ 'Tob.*'`

**Comment by lamoni** [comment]
Okay, thanks!
