### ISSUE TITLE
Error while using createWith in Laravel 5.1 

### ISSUE THREAD

**Issue by korealex** [Vinelab/NeoEloquent#97]
Declaration of Vinelab\NeoEloquent\Eloquent\Relations\HasOneOrMany::saveMany() should be compatible with Illuminate\Database\Eloquent\Relations\HasOneOrMany::saveMany($models) 

looks like saveMany method was added in 5.1 and is causing an error

**Comment by Mulkave** [comment]
Should've been fixed by 1.2.6, please report back if you encounter any issues. Cheers 🍻
